package com.badminton.mes.module.scene.service.impl;
import java.util.*;import com.badminton.mes.common.core.PageResult;import com.badminton.mes.common.exception.ServiceException;
import com.badminton.mes.module.scene.constants.SceneErrorCodeConstants;import com.badminton.mes.module.scene.controller.vo.*;
import com.badminton.mes.module.scene.dal.entity.*;import com.badminton.mes.module.scene.dal.repository.*;
import com.badminton.mes.module.scene.service.*;import org.springframework.data.domain.*;import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.util.StringUtils;import jakarta.persistence.criteria.Predicate;
/** 产品状态查询 Service。 @author 刘涵 */
@Service
public class SceneProductStatusServiceImpl implements SceneProductStatusService {
 private final SceneBatchStatusRepository repository;private final SceneBatchStatusHistoryRepository statusHistoryRepository;
 private final SceneBatchProcessHistoryRepository processHistoryRepository;private final SceneProductionTaskRepository taskRepository;private final SceneDataScopeService dataScope;
 public SceneProductStatusServiceImpl(SceneBatchStatusRepository repository,SceneBatchStatusHistoryRepository statusHistoryRepository,
  SceneBatchProcessHistoryRepository processHistoryRepository,SceneProductionTaskRepository taskRepository,SceneDataScopeService dataScope){
  this.repository=repository;this.statusHistoryRepository=statusHistoryRepository;this.processHistoryRepository=processHistoryRepository;this.taskRepository=taskRepository;this.dataScope=dataScope;}
 @Override @Transactional(readOnly=true) public SceneProductStatusRespVO getByBatch(String batch){SceneBatchStatusEntity e=repository.findByBatchNoAndDeletedFalse(batch).orElseThrow(()->new ServiceException(SceneErrorCodeConstants.TASK_NOT_EXISTS));check(e);return toResp(e);}
 @Override @Transactional(readOnly=true) public PageResult<SceneProductStatusRespVO> page(SceneProductStatusPageReqVO req){Specification<SceneBatchStatusEntity> spec=(root,q,cb)->{List<Predicate> p=new ArrayList<>();p.add(cb.isFalse(root.get("deleted")));if(StringUtils.hasText(req.getBatchNo()))p.add(cb.like(root.get("batchNo"),req.getBatchNo()+"%"));if(req.getTaskId()!=null)p.add(cb.equal(root.get("taskId"),req.getTaskId()));if(req.getBatchStatus()!=null)p.add(cb.equal(root.get("batchStatus"),req.getBatchStatus()));if(req.getAbnormal()!=null)p.add(cb.equal(root.get("abnormal"),req.getAbnormal()));return cb.and(p.toArray(new Predicate[0]));};long total=repository.count(spec);if(total==0)return PageResult.empty(req.getPageNo(),req.getPageSize());int pages=(int)((total+req.getPageSize()-1)/req.getPageSize());int no=Math.min(req.getPageNo(),pages);Page<SceneBatchStatusEntity> page=repository.findAll(spec,PageRequest.of(no-1,req.getPageSize(),Sort.by(Sort.Direction.DESC,"id")));List<SceneProductStatusRespVO> list=page.getContent().stream().filter(e->{try{check(e);return true;}catch(ServiceException x){return false;}}).map(this::toResp).toList();return PageResult.of(list,total,no,req.getPageSize());}
 @Override @Transactional(readOnly=true) public List<SceneStatusHistoryRespVO> histories(Long id){SceneBatchStatusEntity e=require(id);check(e);return statusHistoryRepository.findByBatchStatusIdAndDeletedFalseOrderByOperateTimeDescIdDesc(id).stream().map(h->{SceneStatusHistoryRespVO v=new SceneStatusHistoryRespVO();v.setId(h.getId());v.setFromStatus(h.getFromStatus());v.setToStatus(h.getToStatus());v.setProcessId(h.getProcessId());v.setChangeReason(h.getChangeReason());v.setOperatorId(h.getOperatorId());v.setOperateTime(h.getOperateTime());return v;}).toList();}
 @Override @Transactional(readOnly=true) public List<SceneProcessHistoryRespVO> processHistories(Long id){SceneBatchStatusEntity e=require(id);check(e);return processHistoryRepository.findByBatchStatusIdAndDeletedFalseOrderByOperateTimeDescIdDesc(id).stream().map(h->{SceneProcessHistoryRespVO v=new SceneProcessHistoryRespVO();v.setId(h.getId());v.setDispatchDetailId(h.getDispatchDetailId());v.setProcessId(h.getProcessId());v.setProcessCode(h.getProcessCode());v.setProcessName(h.getProcessName());v.setActionType(h.getActionType());v.setOperatorId(h.getOperatorId());v.setActionReason(h.getActionReason());v.setOperateTime(h.getOperateTime());return v;}).toList();}
 private SceneBatchStatusEntity require(Long id){return repository.findByIdAndDeletedFalse(id).orElseThrow(()->new ServiceException(SceneErrorCodeConstants.TASK_NOT_EXISTS));}
 private void check(SceneBatchStatusEntity e){SceneProductionTaskEntity t=taskRepository.findByIdAndDeletedFalse(e.getTaskId()).orElseThrow(()->new ServiceException(SceneErrorCodeConstants.TASK_NOT_EXISTS));dataScope.check(t.getWorkshopId(),t.getLineId());}
 private SceneProductStatusRespVO toResp(SceneBatchStatusEntity e){SceneProductStatusRespVO v=new SceneProductStatusRespVO();v.setId(e.getId());v.setBatchNo(e.getBatchNo());v.setTaskId(e.getTaskId());v.setProductId(e.getProductId());v.setCurrentProcessId(e.getCurrentProcessId());v.setCurrentProcessName(e.getCurrentProcessName());v.setBatchStatus(e.getBatchStatus());v.setAbnormal(e.getAbnormal());v.setUpdateTime(e.getUpdateTime());return v;}
}
