<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import PageHeader from '@/components/base/PageHeader.vue'
import PermissionButton from '@/components/base/PermissionButton.vue'
import StatusTag from '@/components/base/StatusTag.vue'
import TablePager from '@/components/base/TablePager.vue'
import { useTable } from '@/composables/useTable'
import type { OptionItem } from '@/types/components'
import {
  EQUIPMENT_COMMON_WRITE_ROLES,
  EQUIPMENT_ENABLE_STATUS_MAP,
  EQUIPMENT_ENABLE_STATUS_OPTIONS,
  EQUIPMENT_FAULT_LEVEL_MAP,
  EQUIPMENT_FAULT_LEVEL_OPTIONS,
  EQUIPMENT_MAINTENANCE_RECORD_STATUS_MAP,
  EQUIPMENT_MAINTENANCE_RECORD_STATUS_OPTIONS,
  EQUIPMENT_MAINTENANCE_RESULT_MAP,
  EQUIPMENT_MAINTENANCE_RESULT_OPTIONS,
  EQUIPMENT_MAINTENANCE_TYPE_MAP,
  EQUIPMENT_MAINTENANCE_TYPE_OPTIONS,
  EQUIPMENT_REPAIR_STATUS_MAP,
  EQUIPMENT_REPAIR_STATUS_OPTIONS,
  EQUIPMENT_STATUS_MAP,
  EQUIPMENT_STATUS_OPTIONS,
  MAINTENANCE_PLAN_WRITE_ROLES,
  MAINTENANCE_RECORD_DELETE_ROLES,
  MAINTENANCE_RECORD_READ_WRITE_ROLES,
} from '@/constants/equipment'
import { loadLineOptions, loadWorkshopOptions } from '@/api/production/options'
import { createEquipmentCategory, deleteEquipmentCategory, getEquipmentCategoryPage, updateEquipmentCategory } from '@/api/equipment/category'
import type { EquipmentCategory } from '@/api/equipment/category'
import { createEquipmentManufacturer, deleteEquipmentManufacturer, getEquipmentManufacturerPage, updateEquipmentManufacturer } from '@/api/equipment/manufacturer'
import type { EquipmentManufacturer } from '@/api/equipment/manufacturer'
import { createEquipmentFaultPrinciple, deleteEquipmentFaultPrinciple, getEquipmentFaultPrinciplePage, updateEquipmentFaultPrinciple } from '@/api/equipment/faultPrinciple'
import type { EquipmentFaultPrinciple } from '@/api/equipment/faultPrinciple'
import { createEquipmentLedger, deleteEquipmentLedger, getEquipmentLedgerPage, updateEquipmentLedger } from '@/api/equipment/ledger'
import type { EquipmentLedger } from '@/api/equipment/ledger'
import { createEquipmentMaintenancePlan, deleteEquipmentMaintenancePlan, getEquipmentMaintenancePlanPage, updateEquipmentMaintenancePlan } from '@/api/equipment/maintenancePlan'
import type { EquipmentMaintenancePlan } from '@/api/equipment/maintenancePlan'
import { createEquipmentMaintenanceRecord, deleteEquipmentMaintenanceRecord, getEquipmentMaintenanceRecordPage, updateEquipmentMaintenanceRecord } from '@/api/equipment/maintenanceRecord'
import type { EquipmentMaintenanceRecord } from '@/api/equipment/maintenanceRecord'
import { createEquipmentRepairOrder, deleteEquipmentRepairOrder, getEquipmentRepairOrderPage, updateEquipmentRepairOrder } from '@/api/equipment/repairOrder'
import type { EquipmentRepairOrder } from '@/api/equipment/repairOrder'
import { loadEquipmentCategoryOptions, loadEquipmentFaultPrincipleOptions, loadEquipmentLedgerOptions, loadEquipmentMaintenancePlanOptions, loadEquipmentManufacturerOptions } from '@/api/equipment/options'

defineOptions({ name: 'EquipmentManagement' })
const activeTab = ref('ledgers')
const categoryOptions = ref<OptionItem[]>([]); const manufacturerOptions = ref<OptionItem[]>([]); const faultOptions = ref<OptionItem[]>([]); const equipmentOptions = ref<OptionItem[]>([]); const planOptions = ref<OptionItem[]>([]); const workshopOptions = ref<OptionItem[]>([]); const lineOptions = ref<OptionItem[]>([])
function optionLabel(options: OptionItem[], value: number | null | undefined) { return options.find((item) => item.value === value)?.label ?? (value ? `#${value}` : '-') }
async function reloadOptions() { [categoryOptions.value, manufacturerOptions.value, faultOptions.value, equipmentOptions.value, planOptions.value, workshopOptions.value, lineOptions.value] = await Promise.all([loadEquipmentCategoryOptions(), loadEquipmentManufacturerOptions(), loadEquipmentFaultPrincipleOptions(), loadEquipmentLedgerOptions(), loadEquipmentMaintenancePlanOptions(), loadWorkshopOptions(), loadLineOptions()]) }
onMounted(reloadOptions)
async function remove(label: string, action: () => Promise<void>, refresh: () => Promise<void>, reload = false) { await ElMessageBox.confirm(`确认删除“${label}”？`, '删除确认', { type: 'warning' }); await action(); ElMessage.success('已删除'); await refresh(); if (reload) await reloadOptions() }

const categoryFilters = reactive({ keyword: '', status: undefined as number | undefined }); const categoryTable = useTable({ fetcher: getEquipmentCategoryPage }); const categoryVisible = ref(false); const categoryId = ref<number>(); const categoryForm = reactive({ categoryCode: '', categoryName: '', parentId: undefined as number | undefined, sortOrder: 0, remark: '', status: 1 })
function openCategory(row?: EquipmentCategory | Record<string, any>) { categoryId.value = row?.id; Object.assign(categoryForm, row ? { categoryCode: row.categoryCode, categoryName: row.categoryName, parentId: row.parentId || undefined, sortOrder: row.sortOrder, remark: row.remark || '', status: row.status } : { categoryCode: '', categoryName: '', parentId: undefined, sortOrder: 0, remark: '', status: 1 }); categoryVisible.value = true }
async function saveCategory() { if (!categoryForm.categoryCode || !categoryForm.categoryName) return ElMessage.warning('请填写类别编码和名称'); if (categoryId.value) await updateEquipmentCategory(categoryId.value, categoryForm); else await createEquipmentCategory(categoryForm); ElMessage.success('设备类别已保存'); categoryVisible.value = false; await Promise.all([categoryTable.refresh(), reloadOptions()]) }

const manufacturerFilters = reactive({ keyword: '', status: undefined as number | undefined }); const manufacturerTable = useTable({ fetcher: getEquipmentManufacturerPage }); const manufacturerVisible = ref(false); const manufacturerId = ref<number>(); const manufacturerForm = reactive({ manufacturerCode: '', manufacturerName: '', contactPerson: '', contactPhone: '', contactEmail: '', address: '', website: '', remark: '', status: 1 })
function openManufacturer(row?: EquipmentManufacturer | Record<string, any>) { manufacturerId.value = row?.id; Object.assign(manufacturerForm, row ? { manufacturerCode: row.manufacturerCode, manufacturerName: row.manufacturerName, contactPerson: row.contactPerson || '', contactPhone: row.contactPhone || '', contactEmail: row.contactEmail || '', address: row.address || '', website: row.website || '', remark: row.remark || '', status: row.status } : { manufacturerCode: '', manufacturerName: '', contactPerson: '', contactPhone: '', contactEmail: '', address: '', website: '', remark: '', status: 1 }); manufacturerVisible.value = true }
async function saveManufacturer() { if (!manufacturerForm.manufacturerCode || !manufacturerForm.manufacturerName) return ElMessage.warning('请填写制造商编码和名称'); if (manufacturerId.value) await updateEquipmentManufacturer(manufacturerId.value, manufacturerForm); else await createEquipmentManufacturer(manufacturerForm); ElMessage.success('制造商已保存'); manufacturerVisible.value = false; await Promise.all([manufacturerTable.refresh(), reloadOptions()]) }

const faultFilters = reactive({ keyword: '', categoryId: undefined as number | undefined, faultLevel: undefined as any, status: undefined as number | undefined }); const faultTable = useTable({ fetcher: getEquipmentFaultPrinciplePage }); const faultVisible = ref(false); const faultId = ref<number>(); const faultForm = reactive({ faultCode: '', faultName: '', categoryId: undefined as number | undefined, faultLevel: 'MEDIUM' as any, faultDescription: '', suggestedSolution: '', sortOrder: 0, remark: '', status: 1 })
function openFault(row?: EquipmentFaultPrinciple | Record<string, any>) { faultId.value = row?.id; Object.assign(faultForm, row ? { faultCode: row.faultCode, faultName: row.faultName, categoryId: row.categoryId || undefined, faultLevel: row.faultLevel, faultDescription: row.faultDescription || '', suggestedSolution: row.suggestedSolution || '', sortOrder: row.sortOrder, remark: row.remark || '', status: row.status } : { faultCode: '', faultName: '', categoryId: undefined, faultLevel: 'MEDIUM', faultDescription: '', suggestedSolution: '', sortOrder: 0, remark: '', status: 1 }); faultVisible.value = true }
async function saveFault() { if (!faultForm.faultCode || !faultForm.faultName) return ElMessage.warning('请填写故障编码和名称'); if (faultId.value) await updateEquipmentFaultPrinciple(faultId.value, faultForm); else await createEquipmentFaultPrinciple(faultForm); ElMessage.success('故障原理已保存'); faultVisible.value = false; await Promise.all([faultTable.refresh(), reloadOptions()]) }

const ledgerFilters = reactive({ keyword: '', categoryId: undefined as number | undefined, equipmentStatus: undefined as any, workshopId: undefined as number | undefined, status: undefined as number | undefined }); const ledgerTable = useTable({ fetcher: getEquipmentLedgerPage }); const ledgerVisible = ref(false); const ledgerId = ref<number>(); const ledgerForm = reactive({ equipmentCode: '', equipmentName: '', categoryId: undefined as number | undefined, manufacturerId: undefined as number | undefined, equipmentModel: '', serialNumber: '', workshopId: undefined as number | undefined, productionLineId: undefined as number | undefined, installationLocation: '', purchaseDate: '', commissioningDate: '', equipmentStatus: 'IDLE' as any, responsiblePerson: '', remark: '', status: 1 })
function openLedger(row?: EquipmentLedger | Record<string, any>) { ledgerId.value = row?.id; Object.assign(ledgerForm, row ? { equipmentCode: row.equipmentCode, equipmentName: row.equipmentName, categoryId: row.categoryId, manufacturerId: row.manufacturerId || undefined, equipmentModel: row.equipmentModel || '', serialNumber: row.serialNumber || '', workshopId: row.workshopId || undefined, productionLineId: row.productionLineId || undefined, installationLocation: row.installationLocation || '', purchaseDate: row.purchaseDate || '', commissioningDate: row.commissioningDate || '', equipmentStatus: row.equipmentStatus, responsiblePerson: row.responsiblePerson || '', remark: row.remark || '', status: row.status } : { equipmentCode: '', equipmentName: '', categoryId: undefined, manufacturerId: undefined, equipmentModel: '', serialNumber: '', workshopId: undefined, productionLineId: undefined, installationLocation: '', purchaseDate: '', commissioningDate: '', equipmentStatus: 'IDLE', responsiblePerson: '', remark: '', status: 1 }); ledgerVisible.value = true }
async function saveLedger() { if (!ledgerForm.equipmentCode || !ledgerForm.equipmentName || !ledgerForm.categoryId) return ElMessage.warning('请填写设备编码、名称和类别'); if (ledgerId.value) await updateEquipmentLedger(ledgerId.value, ledgerForm as any); else await createEquipmentLedger(ledgerForm as any); ElMessage.success('设备台账已保存'); ledgerVisible.value = false; await Promise.all([ledgerTable.refresh(), reloadOptions()]) }

const planFilters = reactive({ keyword: '', equipmentId: undefined as number | undefined, maintenanceType: undefined as any, status: undefined as number | undefined }); const planTable = useTable({ fetcher: getEquipmentMaintenancePlanPage }); const planVisible = ref(false); const planId = ref<number>(); const planForm = reactive({ planCode: '', planName: '', equipmentId: undefined as number | undefined, maintenanceType: 'ROUTINE' as any, cycleDays: 30, maintenanceContent: '', responsibleUserId: undefined as number | undefined, nextMaintenanceTime: '', remark: '', status: 1 })
function openPlan(row?: EquipmentMaintenancePlan | Record<string, any>) { planId.value = row?.id; Object.assign(planForm, row ? { planCode: row.planCode, planName: row.planName, equipmentId: row.equipmentId, maintenanceType: row.maintenanceType || 'ROUTINE', cycleDays: row.cycleDays, maintenanceContent: row.maintenanceContent, responsibleUserId: row.responsibleUserId || undefined, nextMaintenanceTime: row.nextMaintenanceTime, remark: row.remark || '', status: row.status ?? 1 } : { planCode: '', planName: '', equipmentId: undefined, maintenanceType: 'ROUTINE', cycleDays: 30, maintenanceContent: '', responsibleUserId: undefined, nextMaintenanceTime: '', remark: '', status: 1 }); planVisible.value = true }
async function savePlan() { if (!planForm.planCode || !planForm.planName || !planForm.equipmentId || !planForm.nextMaintenanceTime || !planForm.maintenanceContent) return ElMessage.warning('请完整填写保养计划'); if (planId.value) await updateEquipmentMaintenancePlan(planId.value, planForm as any); else await createEquipmentMaintenancePlan(planForm as any); ElMessage.success('保养计划已保存'); planVisible.value = false; await Promise.all([planTable.refresh(), reloadOptions()]) }

const recordFilters = reactive({ keyword: '', equipmentId: undefined as number | undefined, recordStatus: undefined as any, maintenanceResult: undefined as any }); const recordTable = useTable({ fetcher: getEquipmentMaintenanceRecordPage }); const recordVisible = ref(false); const recordId = ref<number>(); const recordForm = reactive({ recordNo: '', planId: undefined as number | undefined, scheduledTime: '', startTime: '', finishTime: '', executorUserId: undefined as number | undefined, maintenanceContent: '', maintenanceResult: undefined as any, recordStatus: 'PENDING' as any, abnormalDescription: '', remark: '' })
function openRecord(row?: EquipmentMaintenanceRecord | Record<string, any>) { recordId.value = row?.id; Object.assign(recordForm, row ? { recordNo: row.recordNo || '', planId: row.planId, scheduledTime: row.scheduledTime, startTime: row.startTime || '', finishTime: row.finishTime || '', executorUserId: row.executorUserId || undefined, maintenanceContent: row.maintenanceContent, maintenanceResult: row.maintenanceResult || undefined, recordStatus: row.recordStatus || 'PENDING', abnormalDescription: row.abnormalDescription || '', remark: row.remark || '' } : { recordNo: '', planId: undefined, scheduledTime: '', startTime: '', finishTime: '', executorUserId: undefined, maintenanceContent: '', maintenanceResult: undefined, recordStatus: 'PENDING', abnormalDescription: '', remark: '' }); recordVisible.value = true }
async function saveRecord() { if (!recordForm.planId || !recordForm.scheduledTime || !recordForm.maintenanceContent) return ElMessage.warning('请完整填写保养记录'); if (recordId.value) await updateEquipmentMaintenanceRecord(recordId.value, recordForm as any); else await createEquipmentMaintenanceRecord(recordForm as any); ElMessage.success('保养记录已保存'); recordVisible.value = false; await recordTable.refresh() }

const repairFilters = reactive({ keyword: '', equipmentId: undefined as number | undefined, repairStatus: undefined as any }); const repairTable = useTable({ fetcher: getEquipmentRepairOrderPage }); const repairVisible = ref(false); const repairId = ref<number>(); const repairForm = reactive({ repairNo: '', equipmentId: undefined as number | undefined, faultPrincipleId: undefined as number | undefined, faultDescription: '', reportTime: '', reportUserId: undefined as number | undefined, repairUserId: undefined as number | undefined, repairStartTime: '', repairEndTime: '', repairResult: '', repairStatus: 'REPORTED' as any, remark: '' })
function openRepair(row?: EquipmentRepairOrder | Record<string, any>) { repairId.value = row?.id; Object.assign(repairForm, row ? { repairNo: row.repairNo, equipmentId: row.equipmentId, faultPrincipleId: row.faultPrincipleId || undefined, faultDescription: row.faultDescription, reportTime: row.reportTime, reportUserId: row.reportUserId, repairUserId: row.repairUserId || undefined, repairStartTime: row.repairStartTime || '', repairEndTime: row.repairEndTime || '', repairResult: row.repairResult || '', repairStatus: row.repairStatus, remark: row.remark || '' } : { repairNo: '', equipmentId: undefined, faultPrincipleId: undefined, faultDescription: '', reportTime: '', reportUserId: undefined, repairUserId: undefined, repairStartTime: '', repairEndTime: '', repairResult: '', repairStatus: 'REPORTED', remark: '' }); repairVisible.value = true }
async function saveRepair() { if (!repairForm.equipmentId || !repairForm.faultDescription) return ElMessage.warning('请选择设备并填写故障描述'); if (repairId.value) await updateEquipmentRepairOrder(repairId.value, repairForm as any); else await createEquipmentRepairOrder(repairForm as any); ElMessage.success('报修任务已保存'); repairVisible.value = false; await repairTable.refresh() }
</script>

<template>
  <div class="page-container">
    <PageHeader title="设备管理" description="设备主档、台账、保养计划与记录、故障及报修任务统一管理" />
    <el-card shadow="never"><el-tabs v-model="activeTab">
      <el-tab-pane label="设备台账" name="ledgers"><div class="toolbar"><el-form :inline="true"><el-form-item label="关键词"><el-input v-model="ledgerFilters.keyword" clearable /></el-form-item><el-form-item label="类别"><el-select v-model="ledgerFilters.categoryId" clearable><el-option v-for="o in categoryOptions" :key="o.value" v-bind="o" /></el-select></el-form-item><el-form-item label="设备状态"><el-select v-model="ledgerFilters.equipmentStatus" clearable><el-option v-for="o in EQUIPMENT_STATUS_OPTIONS" :key="o.value" v-bind="o" /></el-select></el-form-item><el-button type="primary" @click="ledgerTable.query(ledgerFilters)">查询</el-button></el-form><PermissionButton :roles="EQUIPMENT_COMMON_WRITE_ROLES" type="primary" @click="openLedger()">新增设备</PermissionButton></div><el-table :data="ledgerTable.data.value" border><el-table-column prop="equipmentCode" label="设备编码" width="140" /><el-table-column prop="equipmentName" label="设备名称" min-width="150" /><el-table-column label="类别" min-width="150"><template #default="{ row }">{{ optionLabel(categoryOptions,row.categoryId) }}</template></el-table-column><el-table-column label="制造商" min-width="150"><template #default="{ row }">{{ optionLabel(manufacturerOptions,row.manufacturerId) }}</template></el-table-column><el-table-column prop="equipmentModel" label="型号" width="120" /><el-table-column label="状态" width="100"><template #default="{ row }"><StatusTag :status="row.equipmentStatus" :status-map="EQUIPMENT_STATUS_MAP" /></template></el-table-column><el-table-column label="启用" width="80"><template #default="{ row }"><StatusTag :status="row.status" :status-map="EQUIPMENT_ENABLE_STATUS_MAP" /></template></el-table-column><el-table-column label="操作" width="130"><template #default="{ row }"><PermissionButton :roles="EQUIPMENT_COMMON_WRITE_ROLES" link @click="openLedger(row)">编辑</PermissionButton><PermissionButton :roles="EQUIPMENT_COMMON_WRITE_ROLES" link type="danger" @click="remove(row.equipmentName,()=>deleteEquipmentLedger(row.id),ledgerTable.refresh,true)">删除</PermissionButton></template></el-table-column></el-table><TablePager :state="ledgerTable" /></el-tab-pane>
      <el-tab-pane label="设备类别" name="categories"><div class="toolbar"><el-form :inline="true"><el-form-item label="关键词"><el-input v-model="categoryFilters.keyword" /></el-form-item><el-form-item label="状态"><el-select v-model="categoryFilters.status" clearable><el-option v-for="o in EQUIPMENT_ENABLE_STATUS_OPTIONS" :key="o.value" v-bind="o" /></el-select></el-form-item><el-button type="primary" @click="categoryTable.query(categoryFilters)">查询</el-button></el-form><PermissionButton :roles="EQUIPMENT_COMMON_WRITE_ROLES" type="primary" @click="openCategory()">新增类别</PermissionButton></div><el-table :data="categoryTable.data.value" border><el-table-column prop="categoryCode" label="编码" width="150" /><el-table-column prop="categoryName" label="名称" min-width="180" /><el-table-column label="上级类别" min-width="160"><template #default="{ row }">{{ optionLabel(categoryOptions,row.parentId) }}</template></el-table-column><el-table-column prop="sortOrder" label="排序" width="80" /><el-table-column prop="remark" label="备注" min-width="180" /><el-table-column label="状态" width="80"><template #default="{ row }"><StatusTag :status="row.status" :status-map="EQUIPMENT_ENABLE_STATUS_MAP" /></template></el-table-column><el-table-column label="操作" width="130"><template #default="{ row }"><el-button link @click="openCategory(row)">编辑</el-button><el-button link type="danger" @click="remove(row.categoryName,()=>deleteEquipmentCategory(row.id),categoryTable.refresh,true)">删除</el-button></template></el-table-column></el-table><TablePager :state="categoryTable" /></el-tab-pane>
      <el-tab-pane label="制造商" name="manufacturers"><div class="toolbar"><el-form :inline="true"><el-form-item label="关键词"><el-input v-model="manufacturerFilters.keyword" /></el-form-item><el-button type="primary" @click="manufacturerTable.query(manufacturerFilters)">查询</el-button></el-form><el-button type="primary" @click="openManufacturer()">新增制造商</el-button></div><el-table :data="manufacturerTable.data.value" border><el-table-column prop="manufacturerCode" label="编码" width="150" /><el-table-column prop="manufacturerName" label="名称" min-width="180" /><el-table-column prop="contactPerson" label="联系人" /><el-table-column prop="contactPhone" label="联系电话" width="140" /><el-table-column prop="address" label="地址" min-width="180" /><el-table-column label="状态" width="80"><template #default="{ row }"><StatusTag :status="row.status" :status-map="EQUIPMENT_ENABLE_STATUS_MAP" /></template></el-table-column><el-table-column label="操作" width="130"><template #default="{ row }"><el-button link @click="openManufacturer(row)">编辑</el-button><el-button link type="danger" @click="remove(row.manufacturerName,()=>deleteEquipmentManufacturer(row.id),manufacturerTable.refresh,true)">删除</el-button></template></el-table-column></el-table><TablePager :state="manufacturerTable" /></el-tab-pane>
      <el-tab-pane label="故障原理" name="faults"><div class="toolbar"><el-form :inline="true"><el-form-item label="关键词"><el-input v-model="faultFilters.keyword" /></el-form-item><el-form-item label="类别"><el-select v-model="faultFilters.categoryId" clearable><el-option v-for="o in categoryOptions" :key="o.value" v-bind="o" /></el-select></el-form-item><el-button type="primary" @click="faultTable.query(faultFilters)">查询</el-button></el-form><el-button type="primary" @click="openFault()">新增故障原理</el-button></div><el-table :data="faultTable.data.value" border><el-table-column prop="faultCode" label="故障编码" width="140" /><el-table-column prop="faultName" label="故障名称" min-width="160" /><el-table-column label="设备类别" min-width="150"><template #default="{ row }">{{ optionLabel(categoryOptions,row.categoryId) }}</template></el-table-column><el-table-column label="级别" width="90"><template #default="{ row }"><StatusTag :status="row.faultLevel" :status-map="EQUIPMENT_FAULT_LEVEL_MAP" /></template></el-table-column><el-table-column prop="suggestedSolution" label="建议方案" min-width="220" /><el-table-column label="状态" width="80"><template #default="{ row }"><StatusTag :status="row.status" :status-map="EQUIPMENT_ENABLE_STATUS_MAP" /></template></el-table-column><el-table-column label="操作" width="130"><template #default="{ row }"><el-button link @click="openFault(row)">编辑</el-button><el-button link type="danger" @click="remove(row.faultName,()=>deleteEquipmentFaultPrinciple(row.id),faultTable.refresh,true)">删除</el-button></template></el-table-column></el-table><TablePager :state="faultTable" /></el-tab-pane>
      <el-tab-pane label="保养计划" name="plans"><div class="toolbar"><el-form :inline="true"><el-form-item label="关键词"><el-input v-model="planFilters.keyword" /></el-form-item><el-form-item label="设备"><el-select v-model="planFilters.equipmentId" clearable><el-option v-for="o in equipmentOptions" :key="o.value" v-bind="o" /></el-select></el-form-item><el-button type="primary" @click="planTable.query(planFilters)">查询</el-button></el-form><PermissionButton :roles="MAINTENANCE_PLAN_WRITE_ROLES" type="primary" @click="openPlan()">新增保养计划</PermissionButton></div><el-table :data="planTable.data.value" border><el-table-column prop="planCode" label="计划编码" width="140" /><el-table-column prop="planName" label="计划名称" min-width="160" /><el-table-column label="设备" min-width="160"><template #default="{ row }">{{ optionLabel(equipmentOptions,row.equipmentId) }}</template></el-table-column><el-table-column label="类型" width="110"><template #default="{ row }"><StatusTag :status="row.maintenanceType" :status-map="EQUIPMENT_MAINTENANCE_TYPE_MAP" /></template></el-table-column><el-table-column prop="cycleDays" label="周期(天)" width="90" /><el-table-column prop="nextMaintenanceTime" label="下次保养" width="170" /><el-table-column label="操作" width="130"><template #default="{ row }"><PermissionButton :roles="MAINTENANCE_PLAN_WRITE_ROLES" link @click="openPlan(row)">编辑</PermissionButton><PermissionButton :roles="MAINTENANCE_PLAN_WRITE_ROLES" link type="danger" @click="remove(row.planName,()=>deleteEquipmentMaintenancePlan(row.id),planTable.refresh,true)">删除</PermissionButton></template></el-table-column></el-table><TablePager :state="planTable" /></el-tab-pane>
      <el-tab-pane label="保养记录" name="records"><div class="toolbar"><el-form :inline="true"><el-form-item label="关键词"><el-input v-model="recordFilters.keyword" /></el-form-item><el-form-item label="设备"><el-select v-model="recordFilters.equipmentId" clearable><el-option v-for="o in equipmentOptions" :key="o.value" v-bind="o" /></el-select></el-form-item><el-button type="primary" @click="recordTable.query(recordFilters)">查询</el-button></el-form><PermissionButton :roles="MAINTENANCE_RECORD_READ_WRITE_ROLES" type="primary" @click="openRecord()">新增保养记录</PermissionButton></div><el-table :data="recordTable.data.value" border><el-table-column prop="recordNo" label="记录编号" width="150" /><el-table-column label="设备" min-width="160"><template #default="{ row }">{{ optionLabel(equipmentOptions,row.equipmentId) }}</template></el-table-column><el-table-column prop="scheduledTime" label="计划时间" width="170" /><el-table-column prop="executorUserId" label="执行人 ID" width="100" /><el-table-column label="结果" width="90"><template #default="{ row }"><StatusTag :status="row.maintenanceResult" :status-map="EQUIPMENT_MAINTENANCE_RESULT_MAP" /></template></el-table-column><el-table-column label="状态" width="100"><template #default="{ row }"><StatusTag :status="row.recordStatus" :status-map="EQUIPMENT_MAINTENANCE_RECORD_STATUS_MAP" /></template></el-table-column><el-table-column label="操作" width="130"><template #default="{ row }"><PermissionButton :roles="MAINTENANCE_RECORD_READ_WRITE_ROLES" link @click="openRecord(row)">编辑</PermissionButton><PermissionButton :roles="MAINTENANCE_RECORD_DELETE_ROLES" link type="danger" @click="remove(row.recordNo||`#${row.id}`,()=>deleteEquipmentMaintenanceRecord(row.id),recordTable.refresh)">删除</PermissionButton></template></el-table-column></el-table><TablePager :state="recordTable" /></el-tab-pane>
      <el-tab-pane label="报修任务" name="repairs"><div class="toolbar"><el-form :inline="true"><el-form-item label="关键词"><el-input v-model="repairFilters.keyword" /></el-form-item><el-form-item label="设备"><el-select v-model="repairFilters.equipmentId" clearable><el-option v-for="o in equipmentOptions" :key="o.value" v-bind="o" /></el-select></el-form-item><el-form-item label="状态"><el-select v-model="repairFilters.repairStatus" clearable><el-option v-for="o in EQUIPMENT_REPAIR_STATUS_OPTIONS" :key="o.value" v-bind="o" /></el-select></el-form-item><el-button type="primary" @click="repairTable.query(repairFilters)">查询</el-button></el-form><el-button type="primary" @click="openRepair()">发起报修</el-button></div><el-table :data="repairTable.data.value" border><el-table-column prop="repairNo" label="报修单号" width="160" /><el-table-column label="设备" min-width="160"><template #default="{ row }">{{ optionLabel(equipmentOptions,row.equipmentId) }}</template></el-table-column><el-table-column prop="faultDescription" label="故障描述" min-width="220" /><el-table-column prop="repairUserId" label="维修人 ID" width="100" /><el-table-column label="状态" width="100"><template #default="{ row }"><StatusTag :status="row.repairStatus" :status-map="EQUIPMENT_REPAIR_STATUS_MAP" /></template></el-table-column><el-table-column prop="reportTime" label="报修时间" width="170" /><el-table-column label="操作" width="130"><template #default="{ row }"><el-button link @click="openRepair(row)">编辑</el-button><el-button link type="danger" @click="remove(row.repairNo,()=>deleteEquipmentRepairOrder(row.id),repairTable.refresh)">删除</el-button></template></el-table-column></el-table><TablePager :state="repairTable" /></el-tab-pane>
    </el-tabs></el-card>

    <el-dialog v-model="categoryVisible" :title="categoryId?'编辑设备类别':'新增设备类别'" width="560px"><el-form :model="categoryForm" label-width="90px"><el-form-item label="类别编码" required><el-input v-model="categoryForm.categoryCode" /></el-form-item><el-form-item label="类别名称" required><el-input v-model="categoryForm.categoryName" /></el-form-item><el-form-item label="上级类别"><el-select v-model="categoryForm.parentId" clearable><el-option v-for="o in categoryOptions" :key="o.value" v-bind="o" /></el-select></el-form-item><el-form-item label="排序"><el-input-number v-model="categoryForm.sortOrder" :min="0" /></el-form-item><el-form-item label="状态"><el-radio-group v-model="categoryForm.status"><el-radio :value="1">启用</el-radio><el-radio :value="0">停用</el-radio></el-radio-group></el-form-item><el-form-item label="备注"><el-input v-model="categoryForm.remark" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="categoryVisible=false">取消</el-button><el-button type="primary" @click="saveCategory">保存</el-button></template></el-dialog>
    <el-dialog v-model="manufacturerVisible" :title="manufacturerId?'编辑制造商':'新增制造商'" width="620px"><el-form :model="manufacturerForm" label-width="90px"><el-form-item label="厂商编码" required><el-input v-model="manufacturerForm.manufacturerCode" /></el-form-item><el-form-item label="厂商名称" required><el-input v-model="manufacturerForm.manufacturerName" /></el-form-item><el-row :gutter="12"><el-col :span="12"><el-form-item label="联系人"><el-input v-model="manufacturerForm.contactPerson" /></el-form-item></el-col><el-col :span="12"><el-form-item label="联系电话"><el-input v-model="manufacturerForm.contactPhone" /></el-form-item></el-col></el-row><el-form-item label="联系邮箱"><el-input v-model="manufacturerForm.contactEmail" /></el-form-item><el-form-item label="地址"><el-input v-model="manufacturerForm.address" /></el-form-item><el-form-item label="网站"><el-input v-model="manufacturerForm.website" /></el-form-item><el-form-item label="备注"><el-input v-model="manufacturerForm.remark" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="manufacturerVisible=false">取消</el-button><el-button type="primary" @click="saveManufacturer">保存</el-button></template></el-dialog>
    <el-dialog v-model="faultVisible" :title="faultId?'编辑故障原理':'新增故障原理'" width="640px"><el-form :model="faultForm" label-width="100px"><el-form-item label="故障编码" required><el-input v-model="faultForm.faultCode" /></el-form-item><el-form-item label="故障名称" required><el-input v-model="faultForm.faultName" /></el-form-item><el-form-item label="设备类别"><el-select v-model="faultForm.categoryId" clearable><el-option v-for="o in categoryOptions" :key="o.value" v-bind="o" /></el-select></el-form-item><el-form-item label="故障级别"><el-select v-model="faultForm.faultLevel"><el-option v-for="o in EQUIPMENT_FAULT_LEVEL_OPTIONS" :key="o.value" v-bind="o" /></el-select></el-form-item><el-form-item label="故障说明"><el-input v-model="faultForm.faultDescription" type="textarea" /></el-form-item><el-form-item label="建议方案"><el-input v-model="faultForm.suggestedSolution" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="faultVisible=false">取消</el-button><el-button type="primary" @click="saveFault">保存</el-button></template></el-dialog>
    <el-dialog v-model="ledgerVisible" :title="ledgerId?'编辑设备台账':'新增设备台账'" width="760px"><el-form :model="ledgerForm" label-width="100px"><el-row :gutter="12"><el-col :span="12"><el-form-item label="设备编码" required><el-input v-model="ledgerForm.equipmentCode" /></el-form-item></el-col><el-col :span="12"><el-form-item label="设备名称" required><el-input v-model="ledgerForm.equipmentName" /></el-form-item></el-col><el-col :span="12"><el-form-item label="设备类别" required><el-select v-model="ledgerForm.categoryId"><el-option v-for="o in categoryOptions" :key="o.value" v-bind="o" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="制造商"><el-select v-model="ledgerForm.manufacturerId" clearable><el-option v-for="o in manufacturerOptions" :key="o.value" v-bind="o" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="型号"><el-input v-model="ledgerForm.equipmentModel" /></el-form-item></el-col><el-col :span="12"><el-form-item label="序列号"><el-input v-model="ledgerForm.serialNumber" /></el-form-item></el-col><el-col :span="12"><el-form-item label="车间"><el-select v-model="ledgerForm.workshopId" clearable><el-option v-for="o in workshopOptions" :key="o.value" v-bind="o" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="产线"><el-select v-model="ledgerForm.productionLineId" clearable><el-option v-for="o in lineOptions" :key="o.value" v-bind="o" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="设备状态"><el-select v-model="ledgerForm.equipmentStatus"><el-option v-for="o in EQUIPMENT_STATUS_OPTIONS" :key="o.value" v-bind="o" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="责任人"><el-input v-model="ledgerForm.responsiblePerson" /></el-form-item></el-col><el-col :span="12"><el-form-item label="采购日期"><el-date-picker v-model="ledgerForm.purchaseDate" value-format="YYYY-MM-DD" /></el-form-item></el-col><el-col :span="12"><el-form-item label="投产日期"><el-date-picker v-model="ledgerForm.commissioningDate" value-format="YYYY-MM-DD" /></el-form-item></el-col></el-row><el-form-item label="安装位置"><el-input v-model="ledgerForm.installationLocation" /></el-form-item><el-form-item label="备注"><el-input v-model="ledgerForm.remark" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="ledgerVisible=false">取消</el-button><el-button type="primary" @click="saveLedger">保存</el-button></template></el-dialog>
    <el-dialog v-model="planVisible" :title="planId?'编辑保养计划':'新增保养计划'" width="680px"><el-form :model="planForm" label-width="110px"><el-form-item label="计划编码" required><el-input v-model="planForm.planCode" /></el-form-item><el-form-item label="计划名称" required><el-input v-model="planForm.planName" /></el-form-item><el-form-item label="设备" required><el-select v-model="planForm.equipmentId"><el-option v-for="o in equipmentOptions" :key="o.value" v-bind="o" /></el-select></el-form-item><el-row><el-col :span="12"><el-form-item label="保养类型"><el-select v-model="planForm.maintenanceType"><el-option v-for="o in EQUIPMENT_MAINTENANCE_TYPE_OPTIONS" :key="o.value" v-bind="o" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="周期(天)"><el-input-number v-model="planForm.cycleDays" :min="1" /></el-form-item></el-col></el-row><el-form-item label="下次保养" required><el-date-picker v-model="planForm.nextMaintenanceTime" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" /></el-form-item><el-form-item label="保养内容" required><el-input v-model="planForm.maintenanceContent" type="textarea" /></el-form-item><el-form-item label="责任人 ID"><el-input-number v-model="planForm.responsibleUserId" :min="1" /></el-form-item></el-form><template #footer><el-button @click="planVisible=false">取消</el-button><el-button type="primary" @click="savePlan">保存</el-button></template></el-dialog>
    <el-dialog v-model="recordVisible" :title="recordId?'编辑保养记录':'新增保养记录'" width="720px"><el-form :model="recordForm" label-width="110px"><el-form-item label="保养计划" required><el-select v-model="recordForm.planId"><el-option v-for="o in planOptions" :key="o.value" v-bind="o" /></el-select></el-form-item><el-form-item label="计划时间" required><el-date-picker v-model="recordForm.scheduledTime" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" /></el-form-item><el-row><el-col :span="12"><el-form-item label="开始时间"><el-date-picker v-model="recordForm.startTime" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" /></el-form-item></el-col><el-col :span="12"><el-form-item label="完成时间"><el-date-picker v-model="recordForm.finishTime" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" /></el-form-item></el-col></el-row><el-form-item label="保养内容" required><el-input v-model="recordForm.maintenanceContent" type="textarea" /></el-form-item><el-row><el-col :span="12"><el-form-item label="执行状态"><el-select v-model="recordForm.recordStatus"><el-option v-for="o in EQUIPMENT_MAINTENANCE_RECORD_STATUS_OPTIONS" :key="o.value" v-bind="o" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="保养结果"><el-select v-model="recordForm.maintenanceResult" clearable><el-option v-for="o in EQUIPMENT_MAINTENANCE_RESULT_OPTIONS" :key="o.value" v-bind="o" /></el-select></el-form-item></el-col></el-row><el-form-item label="异常说明"><el-input v-model="recordForm.abnormalDescription" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="recordVisible=false">取消</el-button><el-button type="primary" @click="saveRecord">保存</el-button></template></el-dialog>
    <el-dialog v-model="repairVisible" :title="repairId?'编辑报修任务':'发起报修'" width="720px"><el-form :model="repairForm" label-width="100px"><el-form-item label="设备" required><el-select v-model="repairForm.equipmentId"><el-option v-for="o in equipmentOptions" :key="o.value" v-bind="o" /></el-select></el-form-item><el-form-item label="故障原理"><el-select v-model="repairForm.faultPrincipleId" clearable><el-option v-for="o in faultOptions" :key="o.value" v-bind="o" /></el-select></el-form-item><el-form-item label="故障描述" required><el-input v-model="repairForm.faultDescription" type="textarea" /></el-form-item><el-row><el-col :span="12"><el-form-item label="报修时间"><el-date-picker v-model="repairForm.reportTime" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" /></el-form-item></el-col><el-col :span="12"><el-form-item label="维修状态"><el-select v-model="repairForm.repairStatus"><el-option v-for="o in EQUIPMENT_REPAIR_STATUS_OPTIONS" :key="o.value" v-bind="o" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="报修人 ID"><el-input-number v-model="repairForm.reportUserId" :min="1" /></el-form-item></el-col><el-col :span="12"><el-form-item label="维修人 ID"><el-input-number v-model="repairForm.repairUserId" :min="1" /></el-form-item></el-col></el-row><el-form-item label="维修结果"><el-input v-model="repairForm.repairResult" type="textarea" /></el-form-item><el-form-item label="备注"><el-input v-model="repairForm.remark" /></el-form-item></el-form><template #footer><el-button @click="repairVisible=false">取消</el-button><el-button type="primary" @click="saveRepair">保存</el-button></template></el-dialog>
  </div>
</template>

<style scoped>
.toolbar { display:flex; align-items:flex-start; justify-content:space-between; gap:12px; }.el-select { min-width: 180px; }
</style>
