-- 安灯管理：类型、处理配置、原因库、现场异常及处理追溯

CREATE TABLE andon_type (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    type_code VARCHAR(32) NOT NULL COMMENT '安灯类型编码',
    type_name VARCHAR(128) NOT NULL COMMENT '安灯类型名称',
    exception_category VARCHAR(32) NOT NULL COMMENT '异常类别：PRODUCTION EQUIPMENT QUALITY MATERIAL NON_PRODUCTION',
    handling_mode VARCHAR(32) NOT NULL COMMENT '处理方式：NO_ACTION SELF_HANDLE ASSISTANCE',
    response_minutes INT DEFAULT NULL COMMENT '响应时限分钟',
    responsible_role_code VARCHAR(32) DEFAULT NULL COMMENT '默认责任角色编码',
    notification_channels VARCHAR(128) DEFAULT NULL COMMENT '通知渠道，逗号分隔',
    light_control_enabled BOOLEAN NOT NULL DEFAULT FALSE COMMENT '是否启用设备灯控',
    enabled_status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用 0停用',
    remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
    create_by BIGINT NOT NULL COMMENT '创建人用户id',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE COMMENT '逻辑删除标记',
    UNIQUE KEY uk_andon_type_code (type_code),
    INDEX idx_andon_type_category_status (exception_category, enabled_status, is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='安灯类型表';

CREATE TABLE andon_configuration (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    andon_type_id BIGINT NOT NULL COMMENT '安灯类型id',
    production_line_id BIGINT DEFAULT NULL COMMENT '适用产线id，空表示全局',
    scope_line_id BIGINT NOT NULL DEFAULT 0 COMMENT '唯一约束产线范围，0表示全局',
    handler_user_id BIGINT DEFAULT NULL COMMENT '指定处理人用户id',
    handler_role_code VARCHAR(32) DEFAULT NULL COMMENT '处理角色编码',
    escalation_user_id BIGINT DEFAULT NULL COMMENT '超时升级用户id',
    escalation_role_code VARCHAR(32) DEFAULT NULL COMMENT '超时升级角色编码',
    response_minutes INT NOT NULL COMMENT '响应时限分钟',
    escalation_minutes INT DEFAULT NULL COMMENT '升级时限分钟',
    notification_channels VARCHAR(128) NOT NULL COMMENT '通知渠道，逗号分隔',
    enabled_status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用 0停用',
    remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
    create_by BIGINT NOT NULL COMMENT '创建人用户id',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE COMMENT '逻辑删除标记',
    UNIQUE KEY uk_andon_config_scope (andon_type_id, scope_line_id, is_deleted),
    INDEX idx_andon_config_match (andon_type_id, production_line_id, enabled_status, is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='安灯异常处理配置表';

CREATE TABLE andon_reason (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    reason_code VARCHAR(32) NOT NULL COMMENT '异常原因编码',
    reason_name VARCHAR(128) NOT NULL COMMENT '异常原因名称',
    andon_type_id BIGINT NOT NULL COMMENT '所属安灯类型id',
    reason_description VARCHAR(500) DEFAULT NULL COMMENT '原因描述',
    enabled_status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用 0停用',
    create_by BIGINT NOT NULL COMMENT '创建人用户id',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE COMMENT '逻辑删除标记',
    UNIQUE KEY uk_andon_reason_code (reason_code),
    INDEX idx_andon_reason_type_status (andon_type_id, enabled_status, is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='安灯异常原因表';

CREATE TABLE andon_event (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    event_no VARCHAR(32) NOT NULL COMMENT '异常单号',
    andon_type_id BIGINT NOT NULL COMMENT '安灯类型id',
    reason_id BIGINT DEFAULT NULL COMMENT '发起时异常原因id',
    actual_reason_id BIGINT DEFAULT NULL COMMENT '处理确认后的实际原因id',
    source_channel VARCHAR(16) NOT NULL COMMENT '来源：WEB TABLET MOBILE SYSTEM',
    severity VARCHAR(16) NOT NULL DEFAULT 'NORMAL' COMMENT '级别：NORMAL MAJOR CRITICAL',
    workshop_id BIGINT DEFAULT NULL COMMENT '车间id',
    production_line_id BIGINT DEFAULT NULL COMMENT '产线id',
    work_order_id BIGINT DEFAULT NULL COMMENT '生产工单id',
    production_task_id BIGINT DEFAULT NULL COMMENT '生产任务id',
    process_id BIGINT DEFAULT NULL COMMENT '工序id',
    equipment_id BIGINT DEFAULT NULL COMMENT '设备台账id',
    quality_record_id BIGINT DEFAULT NULL COMMENT '质量检验单id',
    batch_no VARCHAR(64) DEFAULT NULL COMMENT '产品批次号',
    description VARCHAR(1000) NOT NULL COMMENT '异常描述',
    attachment_urls TEXT DEFAULT NULL COMMENT '附件地址JSON',
    event_status VARCHAR(32) NOT NULL COMMENT '状态：PENDING_CONFIRMATION CONFIRMED PROCESSING WAITING_CLOSE CLOSED',
    assigned_user_id BIGINT DEFAULT NULL COMMENT '当前指派处理人id',
    assigned_role_code VARCHAR(32) DEFAULT NULL COMMENT '当前指派角色编码',
    response_deadline DATETIME DEFAULT NULL COMMENT '响应截止时间',
    escalation_deadline DATETIME DEFAULT NULL COMMENT '升级截止时间',
    timeout_status VARCHAR(16) NOT NULL DEFAULT 'NORMAL' COMMENT '超时状态：NORMAL RESPONSE_OVERDUE ESCALATED',
    light_status VARCHAR(16) NOT NULL DEFAULT 'NOT_REQUIRED' COMMENT '灯控状态：NOT_REQUIRED ON OFF FAILED',
    light_message VARCHAR(255) DEFAULT NULL COMMENT '灯控结果说明',
    processing_result VARCHAR(1000) DEFAULT NULL COMMENT '最终处理结果',
    impact_minutes INT DEFAULT NULL COMMENT '影响时长分钟',
    affected_quantity INT DEFAULT NULL COMMENT '影响数量',
    initiated_by BIGINT NOT NULL COMMENT '发起人用户id',
    confirmed_by BIGINT DEFAULT NULL COMMENT '确认人用户id',
    confirmed_at DATETIME DEFAULT NULL COMMENT '确认时间',
    completed_by BIGINT DEFAULT NULL COMMENT '完成处理人用户id',
    completed_at DATETIME DEFAULT NULL COMMENT '处理完成时间',
    closed_by BIGINT DEFAULT NULL COMMENT '关闭人用户id',
    closed_at DATETIME DEFAULT NULL COMMENT '关闭时间',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE COMMENT '逻辑删除标记',
    UNIQUE KEY uk_andon_event_no (event_no),
    INDEX idx_andon_event_status (event_status, severity, is_deleted),
    INDEX idx_andon_event_type (andon_type_id, is_deleted),
    INDEX idx_andon_event_reason (reason_id, is_deleted),
    INDEX idx_andon_event_actual_reason (actual_reason_id, is_deleted),
    INDEX idx_andon_event_assignee (assigned_user_id, event_status, is_deleted),
    INDEX idx_andon_event_line_time (production_line_id, create_time),
    INDEX idx_andon_event_equipment (equipment_id, event_status),
    INDEX idx_andon_event_response_deadline (event_status, response_deadline),
    INDEX idx_andon_event_escalation_deadline (event_status, escalation_deadline)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='现场安灯异常表';

CREATE TABLE andon_process_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    event_id BIGINT NOT NULL COMMENT '异常单id',
    action_type VARCHAR(32) NOT NULL COMMENT '动作：INITIATE CONFIRM START_PROCESS TRANSFER COMPLETE CLOSE ESCALATE',
    from_status VARCHAR(32) DEFAULT NULL COMMENT '变更前状态',
    to_status VARCHAR(32) NOT NULL COMMENT '变更后状态',
    operator_id BIGINT NOT NULL COMMENT '操作人用户id',
    target_user_id BIGINT DEFAULT NULL COMMENT '转派或升级目标用户id',
    target_role_code VARCHAR(32) DEFAULT NULL COMMENT '转派或升级目标角色',
    action_content VARCHAR(1000) DEFAULT NULL COMMENT '操作说明、措施或结果',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    INDEX idx_andon_log_event_time (event_id, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='安灯异常处理过程表';

CREATE TABLE andon_notification_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    event_id BIGINT NOT NULL COMMENT '异常单id',
    notification_type VARCHAR(16) NOT NULL COMMENT '通知类型：INITIAL ESCALATION STATUS',
    channel VARCHAR(16) NOT NULL COMMENT '渠道：IN_APP SMS WECHAT',
    receiver_user_id BIGINT DEFAULT NULL COMMENT '接收用户id',
    receiver_role_code VARCHAR(32) DEFAULT NULL COMMENT '接收角色编码',
    send_status VARCHAR(16) NOT NULL COMMENT '发送状态：PENDING SENT FAILED SIMULATED',
    send_message VARCHAR(500) DEFAULT NULL COMMENT '发送结果说明',
    sent_at DATETIME DEFAULT NULL COMMENT '发送时间',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    INDEX idx_andon_notification_event (event_id, notification_type),
    INDEX idx_andon_notification_receiver (receiver_user_id, send_status),
    INDEX idx_andon_notification_send_status (send_status, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='安灯异常通知记录表';
