CREATE TABLE IF NOT EXISTS base_production_line (
    id bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
    line_code varchar(32) NOT NULL COMMENT '产线编码',
    line_name varchar(64) NOT NULL COMMENT '产线名称',
    workshop_id bigint unsigned NOT NULL COMMENT '所属车间',
    standard_capacity int unsigned NULL COMMENT '标准日产能',
    status tinyint unsigned NOT NULL DEFAULT 1 COMMENT '状态',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_line_code (line_code),
    KEY idx_workshop_id (workshop_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='产线表';

CREATE TABLE prod_param (
    id bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
    param_code varchar(64) NOT NULL COMMENT '参数编码',
    param_name varchar(128) NOT NULL COMMENT '参数名称',
    param_value varchar(255) NOT NULL COMMENT '参数值',
    value_type tinyint unsigned NOT NULL DEFAULT 1 COMMENT '值类型:1开关 2数量 3枚举 4文本',
    workshop_id bigint unsigned NULL COMMENT '适用车间',
    line_id bigint unsigned NULL COMMENT '适用产线',
    product_id bigint unsigned NULL COMMENT '适用产品',
    scope_workshop_id bigint unsigned GENERATED ALWAYS AS (IFNULL(workshop_id, 0)) STORED,
    scope_line_id bigint unsigned GENERATED ALWAYS AS (IFNULL(line_id, 0)) STORED,
    scope_product_id bigint unsigned GENERATED ALWAYS AS (IFNULL(product_id, 0)) STORED,
    remark varchar(255) NULL COMMENT '参数说明',
    status tinyint unsigned NOT NULL DEFAULT 1 COMMENT '状态:1启用 0停用',
    create_by bigint unsigned NOT NULL COMMENT '创建人',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_code_scope (param_code, scope_workshop_id, scope_line_id, scope_product_id),
    KEY idx_effective_scope (param_code, status, workshop_id, line_id, product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='生产参数配置表';

CREATE TABLE prod_param_change_log (
    id bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
    param_id bigint unsigned NOT NULL COMMENT '参数主键',
    before_value varchar(255) NULL COMMENT '变更前参数值',
    after_value varchar(255) NULL COMMENT '变更后参数值',
    before_status tinyint unsigned NULL COMMENT '变更前状态',
    after_status tinyint unsigned NULL COMMENT '变更后状态',
    change_reason varchar(255) NOT NULL COMMENT '变更原因',
    operator_id bigint unsigned NOT NULL COMMENT '操作人',
    operate_time datetime NOT NULL COMMENT '业务发生时间',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (id),
    KEY idx_param_time (param_id, operate_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='生产参数变更日志';

CREATE TABLE prod_task (
    id bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
    task_no varchar(32) NOT NULL COMMENT '任务单号',
    source_type tinyint unsigned NOT NULL DEFAULT 2 COMMENT '来源:1派工下发 2手工 3导入 4API',
    work_order_id bigint unsigned NOT NULL COMMENT '来源工单',
    work_order_no varchar(32) NOT NULL COMMENT '工单号快照',
    product_id bigint unsigned NOT NULL COMMENT '产品',
    product_code varchar(64) NOT NULL COMMENT '产品编码快照',
    product_name varchar(128) NOT NULL COMMENT '产品名称快照',
    batch_no varchar(64) NOT NULL COMMENT '批次号',
    routing_id bigint unsigned NOT NULL COMMENT '工艺路线',
    routing_code varchar(32) NOT NULL COMMENT '路线编码快照',
    routing_version varchar(16) NOT NULL COMMENT '路线版本快照',
    workshop_id bigint unsigned NOT NULL COMMENT '车间',
    workshop_name varchar(128) NOT NULL COMMENT '车间名称快照',
    line_id bigint unsigned NOT NULL COMMENT '产线',
    line_name varchar(128) NOT NULL COMMENT '产线名称快照',
    shift_id bigint unsigned NULL COMMENT '班次',
    plan_date date NOT NULL COMMENT '计划日期',
    plan_quantity int unsigned NOT NULL COMMENT '计划数量',
    input_quantity int unsigned NOT NULL DEFAULT 0 COMMENT '投入数量',
    good_quantity int unsigned NOT NULL DEFAULT 0 COMMENT '良品数量',
    defect_quantity int unsigned NOT NULL DEFAULT 0 COMMENT '不良数量',
    rework_quantity int unsigned NOT NULL DEFAULT 0 COMMENT '返修数量',
    finish_quantity int unsigned NOT NULL DEFAULT 0 COMMENT '完工数量',
    plan_start_time datetime NOT NULL COMMENT '计划开始时间',
    plan_end_time datetime NOT NULL COMMENT '计划结束时间',
    actual_start_time datetime NULL COMMENT '实际开始时间',
    actual_end_time datetime NULL COMMENT '实际结束时间',
    task_status tinyint unsigned NOT NULL DEFAULT 0 COMMENT '0待审核 1已审核 2已下发 3生产中 4暂停 5已完工 6已关闭 7已取消',
    pause_reason varchar(255) NULL COMMENT '暂停或关闭原因',
    audit_by bigint unsigned NULL COMMENT '审核人',
    audit_time datetime NULL COMMENT '审核时间',
    create_by bigint unsigned NOT NULL COMMENT '创建人',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_task_no (task_no),
    KEY idx_work_order_status (work_order_id, task_status),
    KEY idx_line_date_status (line_id, plan_date, task_status),
    KEY idx_batch_no (batch_no(20))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='生产任务单';

CREATE TABLE prod_task_operate_log (
    id bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
    task_id bigint unsigned NOT NULL COMMENT '任务',
    operate_type tinyint unsigned NOT NULL COMMENT '1开工 2暂停 3恢复 4结束 5审核 6下发 7关闭',
    from_status tinyint unsigned NOT NULL COMMENT '变更前状态',
    to_status tinyint unsigned NOT NULL COMMENT '变更后状态',
    reason varchar(255) NULL COMMENT '原因',
    terminal_type tinyint unsigned NOT NULL DEFAULT 1 COMMENT '1后台 2平板',
    operator_id bigint unsigned NOT NULL COMMENT '操作人',
    operate_time datetime NOT NULL COMMENT '业务发生时间',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (id),
    KEY idx_task_time (task_id, operate_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='任务操作记录';

CREATE TABLE prod_process_dispatch (
    id bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
    dispatch_no varchar(32) NOT NULL COMMENT '派工单号',
    task_id bigint unsigned NOT NULL COMMENT '任务',
    routing_id bigint unsigned NOT NULL COMMENT '路线',
    routing_code varchar(32) NOT NULL COMMENT '路线编码快照',
    routing_version varchar(16) NOT NULL COMMENT '路线版本快照',
    dispatch_status tinyint unsigned NOT NULL DEFAULT 0 COMMENT '0待确认 1已确认 2执行中 3已完成 4已取消',
    create_by bigint unsigned NOT NULL COMMENT '创建人',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_dispatch_no (dispatch_no),
    KEY idx_task_status (task_id, dispatch_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='生产派工单';

CREATE TABLE prod_process_dispatch_detail (
    id bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
    dispatch_id bigint unsigned NOT NULL COMMENT '派工主表',
    task_id bigint unsigned NOT NULL COMMENT '任务',
    process_id bigint unsigned NOT NULL COMMENT '工序',
    process_code varchar(32) NOT NULL COMMENT '工序编码快照',
    process_name varchar(64) NOT NULL COMMENT '工序名称快照',
    seq int unsigned NOT NULL COMMENT '工序顺序',
    is_key tinyint unsigned NOT NULL DEFAULT 0 COMMENT '关键工序',
    is_inspect tinyint unsigned NOT NULL DEFAULT 0 COMMENT '必检工序',
    is_scan tinyint unsigned NOT NULL DEFAULT 0 COMMENT '必须扫码',
    sop_id bigint unsigned NULL COMMENT 'SOP',
    sop_code varchar(32) NULL COMMENT 'SOP编码快照',
    sop_name varchar(128) NULL COMMENT 'SOP名称快照',
    sop_version varchar(16) NULL COMMENT 'SOP版本快照',
    station_id bigint unsigned NULL COMMENT '工位',
    user_id bigint unsigned NULL COMMENT '人员',
    equipment_id bigint unsigned NULL COMMENT '设备',
    plan_quantity int unsigned NOT NULL COMMENT '计划数量',
    good_quantity int unsigned NOT NULL DEFAULT 0 COMMENT '良品数量',
    defect_quantity int unsigned NOT NULL DEFAULT 0 COMMENT '不良数量',
    detail_status tinyint unsigned NOT NULL DEFAULT 0 COMMENT '0待作业 1作业中 2已完成 3异常',
    is_paused tinyint unsigned NOT NULL DEFAULT 0 COMMENT '是否暂停',
    pause_reason varchar(255) NULL COMMENT '暂停原因',
    actual_start_time datetime NULL COMMENT '实际开始时间',
    actual_end_time datetime NULL COMMENT '实际结束时间',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_dispatch_seq (dispatch_id, seq),
    KEY idx_task_status (task_id, detail_status),
    KEY idx_user_status (user_id, detail_status),
    KEY idx_station_status (station_id, detail_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工序派工明细';

CREATE TABLE prod_batch_status (
    id bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
    batch_no varchar(64) NOT NULL COMMENT '批次号',
    task_id bigint unsigned NOT NULL COMMENT '任务',
    product_id bigint unsigned NOT NULL COMMENT '产品',
    current_process_id bigint unsigned NULL COMMENT '当前工序',
    current_process_name varchar(64) NULL COMMENT '当前工序名称快照',
    batch_status tinyint unsigned NOT NULL DEFAULT 1 COMMENT '1在制 2待检 3返修中 4隔离 5已完工 6已报废',
    is_abnormal tinyint unsigned NOT NULL DEFAULT 0 COMMENT '是否异常',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_batch_no (batch_no),
    KEY idx_task_id (task_id),
    KEY idx_status_abnormal (batch_status, is_abnormal)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='产品当前生产状态';

CREATE TABLE prod_batch_status_history (
    id bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
    batch_status_id bigint unsigned NOT NULL COMMENT '当前状态主键',
    task_id bigint unsigned NOT NULL COMMENT '任务',
    batch_no varchar(64) NOT NULL COMMENT '批次号',
    from_status tinyint unsigned NULL COMMENT '原状态',
    to_status tinyint unsigned NOT NULL COMMENT '目标状态',
    process_id bigint unsigned NULL COMMENT '关联工序',
    change_reason varchar(255) NULL COMMENT '原因',
    operator_id bigint unsigned NOT NULL COMMENT '操作人',
    operate_time datetime NOT NULL COMMENT '业务发生时间',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (id),
    KEY idx_batch_time (batch_status_id, operate_time),
    KEY idx_batch_no (batch_no(20))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='产品状态履历';

CREATE TABLE prod_batch_process_history (
    id bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
    batch_status_id bigint unsigned NOT NULL COMMENT '当前状态主键',
    task_id bigint unsigned NOT NULL COMMENT '任务',
    dispatch_detail_id bigint unsigned NOT NULL COMMENT '派工明细',
    batch_no varchar(64) NOT NULL COMMENT '批次号',
    process_id bigint unsigned NOT NULL COMMENT '工序',
    process_code varchar(32) NOT NULL COMMENT '工序编码快照',
    process_name varchar(64) NOT NULL COMMENT '工序名称快照',
    action_type tinyint unsigned NOT NULL COMMENT '1扫码 2开工 3暂停 4恢复 5完工',
    operator_id bigint unsigned NOT NULL COMMENT '操作人',
    action_reason varchar(255) NULL COMMENT '原因',
    operate_time datetime NOT NULL COMMENT '业务发生时间',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (id),
    KEY idx_batch_time (batch_status_id, operate_time),
    KEY idx_detail_time (dispatch_detail_id, operate_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='产品工序履历';
