-- 质量检验业务单据：统一承载首件、末件、巡检、入库检和发货检

CREATE TABLE IF NOT EXISTS quality_inspection_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    inspection_no VARCHAR(32) NOT NULL COMMENT '检验单号',
    inspection_type VARCHAR(32) NOT NULL COMMENT '检验类型',
    plan_id BIGINT NOT NULL COMMENT '检验方案版本id',
    plan_code_snapshot VARCHAR(32) NOT NULL COMMENT '方案编码快照',
    plan_version_snapshot INT NOT NULL COMMENT '方案版本快照',
    work_order_id BIGINT DEFAULT NULL COMMENT '生产工单id',
    source_document_id BIGINT DEFAULT NULL COMMENT '完工单或发货通知id',
    source_document_no VARCHAR(64) DEFAULT NULL COMMENT '来源单号',
    product_id BIGINT DEFAULT NULL COMMENT '产品id',
    customer_id BIGINT DEFAULT NULL COMMENT '客户id',
    production_line_id BIGINT DEFAULT NULL COMMENT '产线id',
    batch_no VARCHAR(64) NOT NULL COMMENT '产品批次号',
    sample_quantity INT NOT NULL COMMENT '抽样数量',
    record_status VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT '状态：DRAFT SUBMITTED',
    conclusion VARCHAR(32) DEFAULT NULL COMMENT '结论：PASS CONCESSION REWORK SCRAP',
    release_status VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '放行状态：PENDING RELEASED BLOCKED',
    nonconformance_description VARCHAR(500) DEFAULT NULL COMMENT '不合格说明',
    disposition VARCHAR(500) DEFAULT NULL COMMENT '处置意见',
    inspector_id BIGINT DEFAULT NULL COMMENT '质检员id',
    inspected_at DATETIME DEFAULT NULL COMMENT '检验时间',
    create_by BIGINT NOT NULL COMMENT '创建人用户id',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE COMMENT '逻辑删除标记',
    UNIQUE KEY uk_quality_inspection_no (inspection_no),
    INDEX idx_quality_record_type_status (inspection_type, record_status, is_deleted),
    INDEX idx_quality_record_work_order (work_order_id, inspection_type, is_deleted),
    INDEX idx_quality_record_batch (batch_no, inspection_type, is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='质量检验单主表';

CREATE TABLE IF NOT EXISTS quality_inspection_result (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    inspection_record_id BIGINT NOT NULL COMMENT '检验单id',
    inspection_item_id BIGINT NOT NULL COMMENT '检验项目id',
    item_code_snapshot VARCHAR(32) NOT NULL COMMENT '项目编码快照',
    item_name_snapshot VARCHAR(128) NOT NULL COMMENT '项目名称快照',
    value_type_snapshot VARCHAR(16) NOT NULL COMMENT '值类型快照',
    unit_snapshot VARCHAR(32) DEFAULT NULL COMMENT '单位快照',
    required_flag BOOLEAN NOT NULL DEFAULT FALSE COMMENT '是否必检快照',
    standard_value_snapshot VARCHAR(128) DEFAULT NULL COMMENT '标准值快照',
    lower_limit_snapshot DECIMAL(18,6) DEFAULT NULL COMMENT '下限快照',
    upper_limit_snapshot DECIMAL(18,6) DEFAULT NULL COMMENT '上限快照',
    judgment_method_snapshot VARCHAR(32) NOT NULL COMMENT '判定方式快照',
    measured_value VARCHAR(255) DEFAULT NULL COMMENT '实测值',
    judgment_result VARCHAR(16) DEFAULT NULL COMMENT '判定：PASS FAIL',
    defect_description VARCHAR(500) DEFAULT NULL COMMENT '不良说明',
    sort_order INT NOT NULL DEFAULT 0 COMMENT '显示顺序',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_quality_record_item (inspection_record_id, inspection_item_id),
    INDEX idx_quality_result_item (inspection_item_id, judgment_result)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='质量检验项目结果表';
