CREATE TABLE prod_report (
    id bigint unsigned NOT NULL AUTO_INCREMENT,
    report_no varchar(32) NOT NULL,
    request_no varchar(64) NOT NULL,
    task_id bigint unsigned NOT NULL,
    dispatch_detail_id bigint unsigned NOT NULL,
    process_id bigint unsigned NOT NULL,
    batch_no varchar(64) NOT NULL,
    barcode_id bigint unsigned NULL,
    report_type tinyint unsigned NOT NULL DEFAULT 1,
    record_type tinyint unsigned NOT NULL DEFAULT 1 COMMENT '1正常 2冲销',
    source_report_id bigint unsigned NULL,
    user_id bigint unsigned NOT NULL,
    equipment_id bigint unsigned NULL,
    station_id bigint unsigned NULL,
    input_quantity int unsigned NOT NULL DEFAULT 0,
    good_quantity int unsigned NOT NULL DEFAULT 0,
    defect_quantity int unsigned NOT NULL DEFAULT 0,
    rework_quantity int unsigned NOT NULL DEFAULT 0,
    source_type tinyint unsigned NOT NULL DEFAULT 1,
    reverse_reason varchar(255) NULL,
    report_time datetime NOT NULL,
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted tinyint unsigned NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_report_no (report_no),
    UNIQUE KEY uk_request_no (request_no),
    UNIQUE KEY uk_source_report (source_report_id),
    KEY idx_task_process (task_id, process_id),
    KEY idx_batch_time (batch_no(20), report_time),
    KEY idx_user_time (user_id, report_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='生产报工主表';

CREATE TABLE prod_report_defect (
    id bigint unsigned NOT NULL AUTO_INCREMENT,
    report_id bigint unsigned NOT NULL,
    defect_reason_id bigint unsigned NOT NULL,
    defect_quantity int unsigned NOT NULL,
    defect_position varchar(64) NULL,
    handle_type tinyint unsigned NOT NULL DEFAULT 1,
    defect_group_no varchar(64) NULL,
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted tinyint unsigned NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_report_id (report_id),
    KEY idx_defect_group_no (defect_group_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='不良报工明细';

CREATE TABLE prod_finish_order (
    id bigint unsigned NOT NULL AUTO_INCREMENT,
    finish_no varchar(32) NOT NULL,
    task_id bigint unsigned NOT NULL,
    work_order_id bigint unsigned NOT NULL,
    product_id bigint unsigned NOT NULL,
    batch_no varchar(64) NOT NULL,
    finish_quantity int unsigned NOT NULL,
    good_quantity int unsigned NOT NULL DEFAULT 0,
    defect_quantity int unsigned NOT NULL DEFAULT 0,
    rework_quantity int unsigned NOT NULL DEFAULT 0,
    finish_status tinyint unsigned NOT NULL DEFAULT 0 COMMENT '0草稿 1待审核 2通过 3驳回',
    audit_by bigint unsigned NULL,
    audit_time datetime NULL,
    audit_remark varchar(255) NULL,
    sync_status tinyint unsigned NOT NULL DEFAULT 0 COMMENT '0待同步 1成功 2失败',
    create_by bigint unsigned NOT NULL,
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted tinyint unsigned NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_finish_no (finish_no),
    UNIQUE KEY uk_task_id (task_id),
    KEY idx_status_sync (finish_status, sync_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='生产完工单';

CREATE TABLE prod_finish_sync_record (
    id bigint unsigned NOT NULL AUTO_INCREMENT,
    finish_order_id bigint unsigned NOT NULL,
    target_system varchar(32) NOT NULL,
    idempotency_key varchar(128) NOT NULL,
    sync_status tinyint unsigned NOT NULL COMMENT '1成功 2失败',
    retry_count int unsigned NOT NULL DEFAULT 0,
    error_summary varchar(500) NULL,
    last_sync_time datetime NOT NULL,
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted tinyint unsigned NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_finish_target (finish_order_id, target_system),
    UNIQUE KEY uk_idempotency_key (idempotency_key),
    KEY idx_status_time (sync_status, last_sync_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='完工外部同步记录';
