"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getTrace = exports.getProductionSummary = exports.getDashboard = void 0;
const http_1 = require("./http");
const getDashboard = (workshopId, lineId) => (0, http_1.request)({ url: '/api/report/mini_app/realtime_dashboard', method: 'GET', data: { workshopId, lineId } });
exports.getDashboard = getDashboard;
const getProductionSummary = (startTime, endTime, workshopId, lineId) => (0, http_1.request)({ url: '/api/report/mini_app/production_analysis', method: 'GET', data: { startTime, endTime, workshopId, lineId } });
exports.getProductionSummary = getProductionSummary;
const getTrace = (batchCode) => (0, http_1.request)({ url: '/api/report/mini_app/product_trace', method: 'GET', data: { batchCode } });
exports.getTrace = getTrace;
