<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import PageHeader from '@/components/base/PageHeader.vue'
import PermissionButton from '@/components/base/PermissionButton.vue'
import StatusTag from '@/components/base/StatusTag.vue'
import TablePager from '@/components/base/TablePager.vue'
import { useTable } from '@/composables/useTable'
import type { OptionItem } from '@/types/components'
import { ENABLE_STATUS_MAP, ENABLE_STATUS_OPTIONS } from '@/constants/production'
import {
  INSPECTION_CONCLUSION_MAP,
  INSPECTION_CONCLUSION_OPTIONS,
  INSPECTION_TYPE_OPTIONS,
  INSPECTION_TYPE_TEXT,
  INSPECTION_VALUE_TYPE_OPTIONS,
  INSPECTION_VALUE_TYPE_TEXT,
  ITEM_JUDGMENT_RESULT_OPTIONS,
  JUDGMENT_METHOD_OPTIONS,
  JUDGMENT_METHOD_TEXT,
  PLAN_STATUS_MAP,
  PLAN_STATUS_OPTIONS,
  QUALITY_WRITE_ROLES,
  RECORD_STATUS_MAP,
  RECORD_STATUS_OPTIONS,
  RELEASE_STATUS_MAP,
} from '@/constants/quality'
import { loadLineOptions, loadProductOptions } from '@/api/production/options'
import { createInspectionCategory, deleteInspectionCategory, getInspectionCategory, getInspectionCategoryPage, updateInspectionCategory } from '@/api/quality/inspectionCategory'
import type { InspectionCategory } from '@/api/quality/inspectionCategory'
import { createInspectionItem, deleteInspectionItem, getInspectionItem, getInspectionItemPage, updateInspectionItem } from '@/api/quality/inspectionItem'
import type { InspectionItem } from '@/api/quality/inspectionItem'
import { auditInspectionPlan, createInspectionPlan, createInspectionPlanVersion, deleteInspectionPlan, disableInspectionPlan, getInspectionPlan, getInspectionPlanPage, updateInspectionPlan } from '@/api/quality/inspectionPlan'
import type { InspectionPlan, InspectionPlanItemSaveReq } from '@/api/quality/inspectionPlan'
import { createInspectionRecord, getInspectionRecord, getInspectionRecordPage, saveInspectionResults, submitInspectionRecord } from '@/api/quality/inspectionRecord'
import type { InspectionRecord } from '@/api/quality/inspectionRecord'
import { loadEffectiveInspectionPlanOptions, loadInspectionCategoryOptions, loadInspectionItemOptions } from '@/api/quality/options'

defineOptions({ name: 'QualityManagement' })
const activeTab = ref('records')
const categoryOptions = ref<OptionItem[]>([]); const itemOptions = ref<OptionItem[]>([]); const planOptions = ref<OptionItem[]>([]); const productOptions = ref<OptionItem[]>([]); const lineOptions = ref<OptionItem[]>([])
function optionLabel(options: OptionItem[], value: number | null | undefined) { return options.find((item) => item.value === value)?.label ?? (value ? `#${value}` : '-') }
async function reloadOptions() { [categoryOptions.value, itemOptions.value, planOptions.value, productOptions.value, lineOptions.value] = await Promise.all([loadInspectionCategoryOptions(), loadInspectionItemOptions(), loadEffectiveInspectionPlanOptions(), loadProductOptions(), loadLineOptions()]) }
onMounted(reloadOptions)
async function confirmDelete(label: string, action: () => Promise<void>, refresh: () => Promise<void>, reload = false) { await ElMessageBox.confirm(`确认删除“${label}”？`, '删除确认', { type: 'warning' }); await action(); ElMessage.success('已删除'); await refresh(); if (reload) await reloadOptions() }

const categoryFilters = reactive({ keyword: '', enabledStatus: undefined as number | undefined }); const categoryTable = useTable({ fetcher: getInspectionCategoryPage }); const categoryVisible = ref(false); const categoryId = ref<number>(); const categoryForm = reactive({ categoryCode: '', categoryName: '', enabledStatus: 1, remark: '' })
async function openCategory(row?: InspectionCategory | Record<string, any>) { categoryId.value = row?.id; const detail = row?.id ? await getInspectionCategory(row.id) : undefined; Object.assign(categoryForm, detail ? { categoryCode: detail.categoryCode, categoryName: detail.categoryName, enabledStatus: detail.enabledStatus, remark: detail.remark || '' } : { categoryCode: '', categoryName: '', enabledStatus: 1, remark: '' }); categoryVisible.value = true }
async function saveCategory() { if (!categoryForm.categoryCode || !categoryForm.categoryName) return ElMessage.warning('请填写分类编码和名称'); if (categoryId.value) await updateInspectionCategory(categoryId.value, categoryForm); else await createInspectionCategory(categoryForm); ElMessage.success('检验分类已保存'); categoryVisible.value = false; await Promise.all([categoryTable.refresh(), reloadOptions()]) }

const itemFilters = reactive({ keyword: '', categoryId: undefined as number | undefined, valueType: '', requiredFlag: undefined as boolean | undefined, enabledStatus: undefined as number | undefined }); const itemTable = useTable({ fetcher: getInspectionItemPage }); const itemVisible = ref(false); const itemId = ref<number>(); const itemForm = reactive({ itemCode: '', itemName: '', categoryId: undefined as number | undefined, valueType: 'NUMERIC', unit: '', standardValue: '', lowerLimit: undefined as number | undefined, upperLimit: undefined as number | undefined, judgmentMethod: 'RANGE', inspectionMethod: '', requiredFlag: true, enabledStatus: 1, remark: '' })
async function openItem(row?: InspectionItem | Record<string, any>) { itemId.value = row?.id; const detail = row?.id ? await getInspectionItem(row.id) : undefined; Object.assign(itemForm, detail ? { itemCode: detail.itemCode, itemName: detail.itemName, categoryId: detail.categoryId, valueType: detail.valueType, unit: detail.unit || '', standardValue: detail.standardValue || '', lowerLimit: detail.lowerLimit ?? undefined, upperLimit: detail.upperLimit ?? undefined, judgmentMethod: detail.judgmentMethod, inspectionMethod: detail.inspectionMethod || '', requiredFlag: detail.requiredFlag, enabledStatus: detail.enabledStatus, remark: detail.remark || '' } : { itemCode: '', itemName: '', categoryId: undefined, valueType: 'NUMERIC', unit: '', standardValue: '', lowerLimit: undefined, upperLimit: undefined, judgmentMethod: 'RANGE', inspectionMethod: '', requiredFlag: true, enabledStatus: 1, remark: '' }); itemVisible.value = true }
async function saveItem() { if (!itemForm.itemCode || !itemForm.itemName || !itemForm.categoryId || !itemForm.valueType || !itemForm.judgmentMethod) return ElMessage.warning('请完整填写检验项目'); if (itemForm.valueType === 'NUMERIC' && itemForm.judgmentMethod === 'RANGE' && (itemForm.lowerLimit === undefined || itemForm.upperLimit === undefined)) return ElMessage.warning('范围判定需要填写上下限'); if (itemId.value) await updateInspectionItem(itemId.value, itemForm as any); else await createInspectionItem(itemForm as any); ElMessage.success('检验项目已保存'); itemVisible.value = false; await Promise.all([itemTable.refresh(), reloadOptions()]) }

const planFilters = reactive({ keyword: '', productId: undefined as number | undefined, inspectionType: '', planStatus: '' }); const planTable = useTable({ fetcher: getInspectionPlanPage }); const planVisible = ref(false); const planId = ref<number>(); const planForm = reactive({ planCode: '', planName: '', productId: undefined as number | undefined, customerId: undefined as number | undefined, inspectionType: 'FIRST_ARTICLE', effectiveDate: '', defaultFlag: false, remark: '', items: [] as InspectionPlanItemSaveReq[] })
function newPlanItem(): InspectionPlanItemSaveReq { return { inspectionItemId: 0, sortOrder: planForm.items.length + 1, sampleQuantity: 1, requiredFlag: true, standardValue: '', lowerLimit: undefined, upperLimit: undefined, judgmentMethod: 'MANUAL' } }
async function openPlan(row?: InspectionPlan | Record<string, any>) { planId.value = row?.id; const detail = row?.id ? await getInspectionPlan(row.id) : undefined; Object.assign(planForm, detail ? { planCode: detail.planCode, planName: detail.planName, productId: detail.productId || undefined, customerId: detail.customerId || undefined, inspectionType: detail.inspectionType, effectiveDate: detail.effectiveDate || '', defaultFlag: detail.defaultFlag, remark: detail.remark || '', items: detail.items.map((item) => ({ inspectionItemId: item.inspectionItemId, sortOrder: item.sortOrder, sampleQuantity: item.sampleQuantity, requiredFlag: item.requiredFlag, standardValue: item.standardValue || '', lowerLimit: item.lowerLimit ?? undefined, upperLimit: item.upperLimit ?? undefined, judgmentMethod: item.judgmentMethod })) } : { planCode: '', planName: '', productId: undefined, customerId: undefined, inspectionType: 'FIRST_ARTICLE', effectiveDate: '', defaultFlag: false, remark: '', items: [newPlanItem()] }); planVisible.value = true }
function removePlanItem(index: number) { planForm.items.splice(index, 1); planForm.items.forEach((item, i) => { item.sortOrder = i + 1 }) }
async function savePlan() { if (!planForm.planCode || !planForm.planName || !planForm.inspectionType || !planForm.items.length || planForm.items.some((item) => !item.inspectionItemId)) return ElMessage.warning('请完整填写方案及检验项目'); const payload = { ...planForm, items: planForm.items.map((item) => ({ ...item })) }; if (planId.value) await updateInspectionPlan(planId.value, payload); else await createInspectionPlan(payload); ElMessage.success('检验方案已保存'); planVisible.value = false; await Promise.all([planTable.refresh(), reloadOptions()]) }
async function planAction(row: InspectionPlan | Record<string, any>, action: 'audit' | 'disable' | 'version') { if (action === 'audit') await auditInspectionPlan(row.id); else if (action === 'disable') await disableInspectionPlan(row.id); else { const id = await createInspectionPlanVersion(row.id); ElMessage.success(`新版本方案 #${id} 已创建`); await planTable.refresh(); return } ElMessage.success('方案状态已更新'); await Promise.all([planTable.refresh(), reloadOptions()]) }

const recordFilters = reactive({ keyword: '', inspectionType: '', recordStatus: '', conclusion: '', productId: undefined as number | undefined, batchNo: '' }); const recordTable = useTable({ fetcher: getInspectionRecordPage }); const recordCreateVisible = ref(false); const recordForm = reactive({ inspectionType: 'FIRST_ARTICLE', planId: undefined as number | undefined, workOrderId: undefined as number | undefined, sourceDocumentId: undefined as number | undefined, sourceDocumentNo: '', productId: undefined as number | undefined, customerId: undefined as number | undefined, productionLineId: undefined as number | undefined, batchNo: '', sampleQuantity: 1 })
function openRecordCreate() { Object.assign(recordForm, { inspectionType: 'FIRST_ARTICLE', planId: undefined, workOrderId: undefined, sourceDocumentId: undefined, sourceDocumentNo: '', productId: undefined, customerId: undefined, productionLineId: undefined, batchNo: '', sampleQuantity: 1 }); recordCreateVisible.value = true }
async function onRecordTypeChange() { planOptions.value = await loadEffectiveInspectionPlanOptions({ inspectionType: recordForm.inspectionType, productId: recordForm.productId }) }
async function createRecord() { if (!recordForm.planId || !recordForm.batchNo || !recordForm.inspectionType) return ElMessage.warning('请选择方案并填写批次'); const id = await createInspectionRecord(recordForm.inspectionType, recordForm as any); ElMessage.success(`检验单 #${id} 已创建`); recordCreateVisible.value = false; await recordTable.refresh(); await openRecordDetail({ id }) }
const recordDetailVisible = ref(false); const recordDetail = ref<InspectionRecord>(); const submitForm = reactive({ conclusion: 'PASS', nonconformanceDescription: '', disposition: '' })
async function openRecordDetail(row: any) { recordDetail.value = await getInspectionRecord(row.id); Object.assign(submitForm, { conclusion: recordDetail.value.conclusion || 'PASS', nonconformanceDescription: recordDetail.value.nonconformanceDescription || '', disposition: recordDetail.value.disposition || '' }); recordDetailVisible.value = true }
async function saveResults() { if (!recordDetail.value) return; await saveInspectionResults(recordDetail.value.id, { results: recordDetail.value.results.map((item) => ({ resultId: item.id, measuredValue: item.measuredValue, judgmentResult: item.judgmentResult, defectDescription: item.defectDescription })) }); ElMessage.success('实测结果已保存'); await openRecordDetail(recordDetail.value) }
async function submitRecord() { if (!recordDetail.value) return; if (recordDetail.value.results.some((item) => item.requiredFlag && !item.measuredValue)) return ElMessage.warning('请先填写所有必检项目的实测值'); await submitInspectionRecord(recordDetail.value.id, submitForm); ElMessage.success('检验单已提交'); recordDetailVisible.value = false; await recordTable.refresh() }
</script>

<template>
  <div class="page-container">
    <PageHeader title="质量管理" description="检验分类、检验项目、标准方案和检验单全过程管理" />
    <el-card shadow="never"><el-tabs v-model="activeTab">
      <el-tab-pane label="检验单" name="records"><div class="toolbar"><el-form :inline="true"><el-form-item label="关键词"><el-input v-model="recordFilters.keyword" /></el-form-item><el-form-item label="检验类型"><el-select v-model="recordFilters.inspectionType" clearable><el-option v-for="o in INSPECTION_TYPE_OPTIONS" :key="o.value" v-bind="o" /></el-select></el-form-item><el-form-item label="状态"><el-select v-model="recordFilters.recordStatus" clearable><el-option v-for="o in RECORD_STATUS_OPTIONS" :key="o.value" v-bind="o" /></el-select></el-form-item><el-form-item label="批次"><el-input v-model="recordFilters.batchNo" /></el-form-item><el-button type="primary" @click="recordTable.query(recordFilters)">查询</el-button></el-form><PermissionButton :roles="QUALITY_WRITE_ROLES" type="primary" @click="openRecordCreate">新建检验单</PermissionButton></div><el-table :data="recordTable.data.value" border><el-table-column prop="inspectionNo" label="检验单号" width="170" /><el-table-column label="类型" width="120"><template #default="{ row }">{{ INSPECTION_TYPE_TEXT[row.inspectionType]||row.inspectionType }}</template></el-table-column><el-table-column prop="planCode" label="方案" width="130" /><el-table-column label="产品" min-width="150"><template #default="{ row }">{{ optionLabel(productOptions,row.productId) }}</template></el-table-column><el-table-column prop="batchNo" label="批次" width="130" /><el-table-column label="单据状态" width="100"><template #default="{ row }"><StatusTag :status="row.recordStatus" :status-map="RECORD_STATUS_MAP" /></template></el-table-column><el-table-column label="检验结论" width="100"><template #default="{ row }"><StatusTag :status="row.conclusion" :status-map="INSPECTION_CONCLUSION_MAP" /></template></el-table-column><el-table-column label="放行" width="90"><template #default="{ row }"><StatusTag :status="row.releaseStatus" :status-map="RELEASE_STATUS_MAP" /></template></el-table-column><el-table-column prop="createTime" label="创建时间" width="170" /><el-table-column label="操作" width="100"><template #default="{ row }"><el-button link @click="openRecordDetail(row)">{{ row.recordStatus==='DRAFT'?'录入检验':'查看详情' }}</el-button></template></el-table-column></el-table><TablePager :state="recordTable" /></el-tab-pane>
      <el-tab-pane label="检验方案" name="plans"><div class="toolbar"><el-form :inline="true"><el-form-item label="关键词"><el-input v-model="planFilters.keyword" /></el-form-item><el-form-item label="类型"><el-select v-model="planFilters.inspectionType" clearable><el-option v-for="o in INSPECTION_TYPE_OPTIONS" :key="o.value" v-bind="o" /></el-select></el-form-item><el-form-item label="状态"><el-select v-model="planFilters.planStatus" clearable><el-option v-for="o in PLAN_STATUS_OPTIONS" :key="o.value" v-bind="o" /></el-select></el-form-item><el-button type="primary" @click="planTable.query(planFilters)">查询</el-button></el-form><PermissionButton :roles="QUALITY_WRITE_ROLES" type="primary" @click="openPlan()">新增方案</PermissionButton></div><el-table :data="planTable.data.value" border><el-table-column prop="planCode" label="方案编码" width="140" /><el-table-column prop="planName" label="方案名称" min-width="170" /><el-table-column label="类型" width="120"><template #default="{ row }">{{ INSPECTION_TYPE_TEXT[row.inspectionType] }}</template></el-table-column><el-table-column label="产品" min-width="150"><template #default="{ row }">{{ optionLabel(productOptions,row.productId) }}</template></el-table-column><el-table-column prop="versionNo" label="版本" width="70" /><el-table-column label="状态" width="90"><template #default="{ row }"><StatusTag :status="row.planStatus" :status-map="PLAN_STATUS_MAP" /></template></el-table-column><el-table-column label="默认" width="70"><template #default="{ row }">{{ row.defaultFlag?'是':'否' }}</template></el-table-column><el-table-column label="操作" width="300"><template #default="{ row }"><el-button link @click="openPlan(row)">详情</el-button><PermissionButton v-if="row.planStatus==='DRAFT'" :roles="QUALITY_WRITE_ROLES" link @click="openPlan(row)">编辑</PermissionButton><PermissionButton v-if="row.planStatus==='DRAFT'" :roles="QUALITY_WRITE_ROLES" link type="success" @click="planAction(row,'audit')">审核生效</PermissionButton><PermissionButton v-if="row.planStatus==='EFFECTIVE'" :roles="QUALITY_WRITE_ROLES" link type="warning" @click="planAction(row,'disable')">停用</PermissionButton><PermissionButton v-if="row.planStatus!=='DRAFT'" :roles="QUALITY_WRITE_ROLES" link @click="planAction(row,'version')">新版本</PermissionButton><PermissionButton v-if="row.planStatus==='DRAFT'" :roles="QUALITY_WRITE_ROLES" link type="danger" @click="confirmDelete(row.planName,()=>deleteInspectionPlan(row.id),planTable.refresh,true)">删除</PermissionButton></template></el-table-column></el-table><TablePager :state="planTable" /></el-tab-pane>
      <el-tab-pane label="检验项目" name="items"><div class="toolbar"><el-form :inline="true"><el-form-item label="关键词"><el-input v-model="itemFilters.keyword" /></el-form-item><el-form-item label="分类"><el-select v-model="itemFilters.categoryId" clearable><el-option v-for="o in categoryOptions" :key="o.value" v-bind="o" /></el-select></el-form-item><el-form-item label="值类型"><el-select v-model="itemFilters.valueType" clearable><el-option v-for="o in INSPECTION_VALUE_TYPE_OPTIONS" :key="o.value" v-bind="o" /></el-select></el-form-item><el-button type="primary" @click="itemTable.query(itemFilters)">查询</el-button></el-form><PermissionButton :roles="QUALITY_WRITE_ROLES" type="primary" @click="openItem()">新增项目</PermissionButton></div><el-table :data="itemTable.data.value" border><el-table-column prop="itemCode" label="项目编码" width="140" /><el-table-column prop="itemName" label="项目名称" min-width="160" /><el-table-column prop="categoryName" label="分类" width="130" /><el-table-column label="值类型" width="90"><template #default="{ row }">{{ INSPECTION_VALUE_TYPE_TEXT[row.valueType] }}</template></el-table-column><el-table-column prop="unit" label="单位" width="70" /><el-table-column label="标准" min-width="150"><template #default="{ row }">{{ row.judgmentMethod==='RANGE'?`${row.lowerLimit??'-'} ~ ${row.upperLimit??'-'}`:(row.standardValue||'-') }}</template></el-table-column><el-table-column label="判定" width="110"><template #default="{ row }">{{ JUDGMENT_METHOD_TEXT[row.judgmentMethod] }}</template></el-table-column><el-table-column label="必检" width="70"><template #default="{ row }">{{ row.requiredFlag?'是':'否' }}</template></el-table-column><el-table-column label="状态" width="80"><template #default="{ row }"><StatusTag :status="row.enabledStatus" :status-map="ENABLE_STATUS_MAP" /></template></el-table-column><el-table-column label="操作" width="130"><template #default="{ row }"><PermissionButton :roles="QUALITY_WRITE_ROLES" link @click="openItem(row)">编辑</PermissionButton><PermissionButton :roles="QUALITY_WRITE_ROLES" link type="danger" @click="confirmDelete(row.itemName,()=>deleteInspectionItem(row.id),itemTable.refresh,true)">删除</PermissionButton></template></el-table-column></el-table><TablePager :state="itemTable" /></el-tab-pane>
      <el-tab-pane label="检验分类" name="categories"><div class="toolbar"><el-form :inline="true"><el-form-item label="关键词"><el-input v-model="categoryFilters.keyword" /></el-form-item><el-form-item label="状态"><el-select v-model="categoryFilters.enabledStatus" clearable><el-option v-for="o in ENABLE_STATUS_OPTIONS" :key="o.value" v-bind="o" /></el-select></el-form-item><el-button type="primary" @click="categoryTable.query(categoryFilters)">查询</el-button></el-form><PermissionButton :roles="QUALITY_WRITE_ROLES" type="primary" @click="openCategory()">新增分类</PermissionButton></div><el-table :data="categoryTable.data.value" border><el-table-column prop="categoryCode" label="分类编码" width="150" /><el-table-column prop="categoryName" label="分类名称" min-width="180" /><el-table-column prop="remark" label="备注" min-width="220" /><el-table-column label="状态" width="80"><template #default="{ row }"><StatusTag :status="row.enabledStatus" :status-map="ENABLE_STATUS_MAP" /></template></el-table-column><el-table-column prop="updateTime" label="更新时间" width="170" /><el-table-column label="操作" width="130"><template #default="{ row }"><PermissionButton :roles="QUALITY_WRITE_ROLES" link @click="openCategory(row)">编辑</PermissionButton><PermissionButton :roles="QUALITY_WRITE_ROLES" link type="danger" @click="confirmDelete(row.categoryName,()=>deleteInspectionCategory(row.id),categoryTable.refresh,true)">删除</PermissionButton></template></el-table-column></el-table><TablePager :state="categoryTable" /></el-tab-pane>
    </el-tabs></el-card>

    <el-dialog v-model="categoryVisible" :title="categoryId?'编辑检验分类':'新增检验分类'" width="560px"><el-form :model="categoryForm" label-width="90px"><el-form-item label="分类编码" required><el-input v-model="categoryForm.categoryCode" /></el-form-item><el-form-item label="分类名称" required><el-input v-model="categoryForm.categoryName" /></el-form-item><el-form-item label="状态"><el-radio-group v-model="categoryForm.enabledStatus"><el-radio :value="1">启用</el-radio><el-radio :value="0">停用</el-radio></el-radio-group></el-form-item><el-form-item label="备注"><el-input v-model="categoryForm.remark" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="categoryVisible=false">取消</el-button><el-button type="primary" @click="saveCategory">保存</el-button></template></el-dialog>
    <el-dialog v-model="itemVisible" :title="itemId?'编辑检验项目':'新增检验项目'" width="720px"><el-form :model="itemForm" label-width="100px"><el-row :gutter="12"><el-col :span="12"><el-form-item label="项目编码" required><el-input v-model="itemForm.itemCode" /></el-form-item></el-col><el-col :span="12"><el-form-item label="项目名称" required><el-input v-model="itemForm.itemName" /></el-form-item></el-col><el-col :span="12"><el-form-item label="项目分类" required><el-select v-model="itemForm.categoryId"><el-option v-for="o in categoryOptions" :key="o.value" v-bind="o" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="值类型" required><el-select v-model="itemForm.valueType"><el-option v-for="o in INSPECTION_VALUE_TYPE_OPTIONS" :key="o.value" v-bind="o" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="判定方式" required><el-select v-model="itemForm.judgmentMethod"><el-option v-for="o in JUDGMENT_METHOD_OPTIONS" :key="o.value" v-bind="o" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="单位"><el-input v-model="itemForm.unit" /></el-form-item></el-col><el-col :span="8"><el-form-item label="标准值"><el-input v-model="itemForm.standardValue" /></el-form-item></el-col><el-col :span="8"><el-form-item label="下限"><el-input-number v-model="itemForm.lowerLimit" /></el-form-item></el-col><el-col :span="8"><el-form-item label="上限"><el-input-number v-model="itemForm.upperLimit" /></el-form-item></el-col></el-row><el-form-item label="检验方法"><el-input v-model="itemForm.inspectionMethod" type="textarea" /></el-form-item><el-form-item label="必检"><el-switch v-model="itemForm.requiredFlag" /></el-form-item><el-form-item label="备注"><el-input v-model="itemForm.remark" /></el-form-item></el-form><template #footer><el-button @click="itemVisible=false">取消</el-button><el-button type="primary" @click="saveItem">保存</el-button></template></el-dialog>
    <el-dialog v-model="planVisible" :title="planId?'检验方案详情/编辑':'新增检验方案'" width="920px"><el-form :model="planForm" label-width="90px"><el-row :gutter="12"><el-col :span="8"><el-form-item label="方案编码" required><el-input v-model="planForm.planCode" /></el-form-item></el-col><el-col :span="8"><el-form-item label="方案名称" required><el-input v-model="planForm.planName" /></el-form-item></el-col><el-col :span="8"><el-form-item label="检验类型" required><el-select v-model="planForm.inspectionType"><el-option v-for="o in INSPECTION_TYPE_OPTIONS" :key="o.value" v-bind="o" /></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="产品"><el-select v-model="planForm.productId" clearable><el-option v-for="o in productOptions" :key="o.value" v-bind="o" /></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="生效日期"><el-date-picker v-model="planForm.effectiveDate" value-format="YYYY-MM-DD" /></el-form-item></el-col><el-col :span="8"><el-form-item label="默认方案"><el-switch v-model="planForm.defaultFlag" /></el-form-item></el-col></el-row></el-form><div class="detail-toolbar"><strong>检验项目明细</strong><el-button size="small" @click="planForm.items.push(newPlanItem())">添加项目</el-button></div><el-table :data="planForm.items" border><el-table-column label="检验项目" min-width="180"><template #default="{ row }"><el-select v-model="row.inspectionItemId"><el-option v-for="o in itemOptions" :key="o.value" v-bind="o" /></el-select></template></el-table-column><el-table-column label="抽样数" width="110"><template #default="{ row }"><el-input-number v-model="row.sampleQuantity" :min="1" /></template></el-table-column><el-table-column label="判定方式" width="150"><template #default="{ row }"><el-select v-model="row.judgmentMethod"><el-option v-for="o in JUDGMENT_METHOD_OPTIONS" :key="o.value" v-bind="o" /></el-select></template></el-table-column><el-table-column label="标准值" width="120"><template #default="{ row }"><el-input v-model="row.standardValue" /></template></el-table-column><el-table-column label="下限" width="110"><template #default="{ row }"><el-input-number v-model="row.lowerLimit" /></template></el-table-column><el-table-column label="上限" width="110"><template #default="{ row }"><el-input-number v-model="row.upperLimit" /></template></el-table-column><el-table-column label="必检" width="70"><template #default="{ row }"><el-switch v-model="row.requiredFlag" /></template></el-table-column><el-table-column width="60"><template #default="{ $index }"><el-button link type="danger" @click="removePlanItem($index)">删</el-button></template></el-table-column></el-table><template #footer><el-button @click="planVisible=false">取消</el-button><PermissionButton :roles="QUALITY_WRITE_ROLES" type="primary" @click="savePlan">保存</PermissionButton></template></el-dialog>
    <el-dialog v-model="recordCreateVisible" title="新建检验单" width="700px"><el-form :model="recordForm" label-width="100px"><el-row :gutter="12"><el-col :span="12"><el-form-item label="检验类型" required><el-select v-model="recordForm.inspectionType" @change="onRecordTypeChange"><el-option v-for="o in INSPECTION_TYPE_OPTIONS" :key="o.value" v-bind="o" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="检验方案" required><el-select v-model="recordForm.planId"><el-option v-for="o in planOptions" :key="o.value" v-bind="o" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="产品"><el-select v-model="recordForm.productId" clearable @change="onRecordTypeChange"><el-option v-for="o in productOptions" :key="o.value" v-bind="o" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="生产线"><el-select v-model="recordForm.productionLineId" clearable><el-option v-for="o in lineOptions" :key="o.value" v-bind="o" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="批次" required><el-input v-model="recordForm.batchNo" /></el-form-item></el-col><el-col :span="12"><el-form-item label="抽样数量"><el-input-number v-model="recordForm.sampleQuantity" :min="1" /></el-form-item></el-col><el-col :span="12"><el-form-item label="工单 ID"><el-input-number v-model="recordForm.workOrderId" :min="1" /></el-form-item></el-col><el-col :span="12"><el-form-item label="来源单号"><el-input v-model="recordForm.sourceDocumentNo" /></el-form-item></el-col></el-row></el-form><template #footer><el-button @click="recordCreateVisible=false">取消</el-button><el-button type="primary" @click="createRecord">创建</el-button></template></el-dialog>
    <el-drawer v-model="recordDetailVisible" title="检验单录入与判定" size="900px"><template v-if="recordDetail"><el-descriptions :column="3" border><el-descriptions-item label="检验单号">{{ recordDetail.inspectionNo }}</el-descriptions-item><el-descriptions-item label="类型">{{ INSPECTION_TYPE_TEXT[recordDetail.inspectionType] }}</el-descriptions-item><el-descriptions-item label="批次">{{ recordDetail.batchNo }}</el-descriptions-item><el-descriptions-item label="方案">{{ recordDetail.planCode }} V{{ recordDetail.planVersion }}</el-descriptions-item><el-descriptions-item label="状态"><StatusTag :status="recordDetail.recordStatus" :status-map="RECORD_STATUS_MAP" /></el-descriptions-item><el-descriptions-item label="结论"><StatusTag :status="recordDetail.conclusion" :status-map="INSPECTION_CONCLUSION_MAP" /></el-descriptions-item></el-descriptions><el-table :data="recordDetail.results" border class="result-table"><el-table-column prop="itemCode" label="编码" width="110" /><el-table-column prop="itemName" label="检验项目" min-width="140" /><el-table-column label="标准" min-width="120"><template #default="{ row }">{{ row.standardValue||`${row.lowerLimit??'-'} ~ ${row.upperLimit??'-'}` }}</template></el-table-column><el-table-column label="实测值" width="150"><template #default="{ row }"><el-input v-model="row.measuredValue" :disabled="recordDetail.recordStatus!=='DRAFT'" /></template></el-table-column><el-table-column label="单项判定" width="140"><template #default="{ row }"><el-select v-model="row.judgmentResult" :disabled="recordDetail.recordStatus!=='DRAFT'"><el-option v-for="o in ITEM_JUDGMENT_RESULT_OPTIONS" :key="o.value" v-bind="o" /></el-select></template></el-table-column><el-table-column label="缺陷说明" min-width="150"><template #default="{ row }"><el-input v-model="row.defectDescription" :disabled="recordDetail.recordStatus!=='DRAFT'" /></template></el-table-column></el-table><template v-if="recordDetail.recordStatus==='DRAFT'"><PermissionButton :roles="QUALITY_WRITE_ROLES" @click="saveResults">保存实测结果</PermissionButton><el-divider>提交判定</el-divider><el-form :model="submitForm" label-width="90px"><el-form-item label="检验结论"><el-select v-model="submitForm.conclusion"><el-option v-for="o in INSPECTION_CONCLUSION_OPTIONS" :key="o.value" v-bind="o" /></el-select></el-form-item><el-form-item label="不合格说明"><el-input v-model="submitForm.nonconformanceDescription" type="textarea" /></el-form-item><el-form-item label="处置方式"><el-input v-model="submitForm.disposition" /></el-form-item><PermissionButton :roles="QUALITY_WRITE_ROLES" type="primary" @click="submitRecord">提交检验单</PermissionButton></el-form></template></template></el-drawer>
  </div>
</template>

<style scoped>
.toolbar { display:flex; align-items:flex-start; justify-content:space-between; gap:12px; }.el-select { min-width:170px; }.detail-toolbar { display:flex; justify-content:space-between; align-items:center; margin:12px 0; }.result-table { margin:16px 0; }
</style>
